In [1]:
import os
import pandas as pd
from pathlib import Path
from datetime import datetime

def scan_project_directory(root_dir):
    records = []
    root_path = Path(root_dir).resolve()
    
    for dirpath, _, filenames in os.walk(root_path):
        for filename in filenames:
            try:
                filepath = Path(dirpath) / filename
                stat = filepath.stat()
                records.append({
                    "relative_path": str(filepath.relative_to(root_path)),
                    "absolute_path": str(filepath),
                    "name": filename,
                    "extension": filepath.suffix.lower(),
                    "size_MB": round(stat.st_size / (1024 * 1024), 3),
                    "last_modified": datetime.fromtimestamp(stat.st_mtime),
                    "last_accessed": datetime.fromtimestamp(stat.st_atime),
                    "created": datetime.fromtimestamp(stat.st_ctime),
                })
            except Exception as e:
                print(f"⚠️ Error reading {filepath}: {e}")

    df = pd.DataFrame(records)
    return df.sort_values(by="size_MB", ascending=False).reset_index(drop=True)

# 🔍 Scan current project directory (or replace '.' with a specific path)
file_df = scan_project_directory(".")
file_df.head(20)  # Show top 20 largest files

,relative_path,absolute_path,name,extension,size_MB,last_modified,last_accessed,created
0,Downloads/wormbase_full_release/hub/ws268.hal,/home/rohit/Desktop/Projects/C-Elegans/Downloa...,ws268.hal,.hal,2454.646,2025-05-27 06:45:00.000000,2025-08-07 07:49:19.597274,2025-08-07 06:26:01.908499
1,Downloads/wormbase_full_release/database.297.4...,/home/rohit/Desktop/Projects/C-Elegans/Downloa...,database.297.4-16.tar.gz,.gz,1201.947,2025-05-27 06:42:00.000000,2025-08-08 11:16:16.283029,2025-08-07 06:25:23.231679
2,Downloads/wormbase_full_release/database.297.4...,/home/rohit/Desktop/Projects/C-Elegans/Downloa...,database.297.4-2.tar.gz,.gz,990.819,2025-05-27 06:42:00.000000,2025-08-08 11:16:16.931042,2025-08-07 06:22:36.856143
3,_extracted_tars/database.297.4-3/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block13.wrm,.wrm,976.500,2025-05-19 23:27:04.000000,2025-05-19 23:27:04.000000,2025-08-07 13:48:52.375194
4,_extracted_tars/database.297.4-5/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block24.wrm,.wrm,976.500,2025-05-19 23:25:57.000000,2025-05-19 23:25:57.000000,2025-08-07 13:53:57.821479
5,_extracted_tars/database.297.4-5/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block23.wrm,.wrm,976.500,2025-05-19 23:25:57.000000,2025-05-19 23:25:57.000000,2025-08-07 13:53:27.584856
6,_extracted_tars/database.297.4-15/database/blo...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block74.wrm,.wrm,976.500,2025-05-19 23:26:58.000000,2025-05-19 23:26:58.000000,2025-08-07 14:21:52.294432
7,_extracted_tars/database.297.4-15/database/blo...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block75.wrm,.wrm,976.500,2025-05-19 23:27:03.000000,2025-05-19 23:27:03.000000,2025-08-07 14:22:09.934935
8,_extracted_tars/database.297.4-15/database/blo...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block73.wrm,.wrm,976.500,2025-05-19 12:16:32.000000,2025-05-19 12:16:32.000000,2025-08-07 14:21:33.761939
9,_extracted_tars/database.297.4-15/database/blo...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block71.wrm,.wrm,976.500,2025-05-17 07:18:52.000000,2025-05-17 07:18:52.000000,2025-08-07 14:21:25.993747
10,_extracted_tars/database.297.4-15/database/blo...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block72.wrm,.wrm,976.500,2025-05-19 12:17:21.000000,2025-05-19 12:17:21.000000,2025-08-07 14:21:29.813840
11,Unpacked/database_297_4-1_tar/database/block3.wrm,/home/rohit/Desktop/Projects/C-Elegans/Unpacke...,block3.wrm,.wrm,976.500,2025-05-23 07:20:03.000000,2025-05-23 07:20:03.000000,2025-08-07 07:12:43.725837
12,_extracted_tars/database.297.4-3/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block15.wrm,.wrm,976.500,2025-05-19 23:25:16.000000,2025-05-19 23:25:16.000000,2025-08-07 13:49:14.151641
13,_extracted_tars/database.297.4-3/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block14.wrm,.wrm,976.500,2025-05-19 23:27:04.000000,2025-05-19 23:27:04.000000,2025-08-07 13:49:03.167416
14,_extracted_tars/database.297.4-5/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block22.wrm,.wrm,976.500,2025-05-19 23:25:57.000000,2025-05-19 23:25:57.000000,2025-08-07 13:52:54.260170
15,_extracted_tars/database.297.4-3/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block11.wrm,.wrm,976.500,2025-05-19 14:41:04.000000,2025-05-19 14:41:04.000000,2025-08-07 14:10:43.798222
16,_extracted_tars/database.297.4-3/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block12.wrm,.wrm,976.500,2025-08-07 14:10:52.058393,2025-05-19 14:41:25.000000,2025-08-07 14:10:52.058393
17,_extracted_tars/database.297.4-2/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block10.wrm,.wrm,976.500,2025-05-19 14:41:04.000000,2025-05-19 14:41:04.000000,2025-08-07 13:47:42.413756
18,_extracted_tars/database.297.4-2/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block7.wrm,.wrm,976.500,2025-08-07 14:10:56.302480,2025-05-23 07:20:03.000000,2025-08-07 14:10:56.302480
19,_extracted_tars/database.297.4-2/database/bloc...,/home/rohit/Desktop/Projects/C-Elegans/_extrac...,block6.wrm,.wrm,976.500,2025-08-07 14:22:14.223062,2025-05-23 07:20:25.000000,2025-08-07 14:22:14.223062

In [2]:
from collections import defaultdict

def count_files_by_directory(root_dir="."):
    dir_counts = defaultdict(int)
    for dirpath, _, filenames in os.walk(root_dir):
        rel_path = os.path.relpath(dirpath, root_dir)
        file_count = len(filenames)
        dir_counts[rel_path] += file_count
    return pd.DataFrame([
        {"folder": k, "file_count": v}
        for k, v in sorted(dir_counts.items(), key=lambda x: -x[1])
    ])

dir_summary = count_files_by_directory(".")
dir_summary.head(20)  # Show top 20 most crowded folders

                                               folder  file_count
0                                           data/temp         877
1                           data/neuroml/cell_library         713
2   _extracted_txt/Ce_synapse_UNIX/Ce_synapse/Whit...         211
3             _extracted_tars/database.297.4-0/wquery         138
4                                                   .          65
5                     Downloads/wormbase_full_release          53
6         Downloads/wormbase_full_release/hub/remanei          49
7         Downloads/wormbase_full_release/hub/elegans          45
8        Downloads/wormbase_full_release/hub/brenneri          44
9        Downloads/wormbase_full_release/hub/japonica          44
10       Downloads/wormbase_full_release/hub/briggsae          44
11      Downloads/wormbase_full_release/hub/ovolvulus          44
12  Downloads/wormbase_full_release/c_elegans/PRJN...          44
13         Downloads/wormbase_full_release/hub/brugia          36
14    _extracted_tars/database.297.4-0/wquery/geneace          33
15  _extracted_txt/Ce_synapse_UNIX/Ce_synapse/Whit...          32
16        Downloads/wormbase_full_release/hub/s_ratti          30
17  Downloads/wormbase_full_release/c_elegans/PRJN...          30
18  _extracted_tars/database.297.4-0/wquery/geneac...          30
19        Downloads/wormbase_full_release/hub/brugia3          27

In [3]:
# Count file types (extensions) overall
ext_counts = file_df["extension"].value_counts().reset_index()
ext_counts.columns = ["extension", "count"]
ext_counts.head(20)

        extension  count
0                    828
1            .xml    703
2            .nml    691
3             .gz    538
4            .txt    310
5             .bb    240
6            .def    198
7           .html    109
8            .wrm     94
9   .html?c=d;o=a     86
10  .html?c=n;o=d     86
11  .html?c=s;o=a     86
12  .html?c=m;o=a     86
13  .html?c=d;o=d     76
14  .html?c=s;o=d     76
15  .html?c=n;o=a     76
16  .html?c=m;o=d     76
17           .csv     73
18            .py     72
19        .sample     26

In [7]:
import pandas as pd
from pathlib import Path

# 🧠 Function to scan all .csv files and extract column names
def list_csv_columns(root_dir="."):
    csv_info = []
    for path in Path(root_dir).rglob("*.csv"):
        try:
            df = pd.read_csv(path, nrows=0)  # Only reads header
            csv_info.append({
                "file": str(path.relative_to(root_dir)),
                "columns": list(df.columns)
            })
        except Exception as e:
            csv_info.append({
                "file": str(path.relative_to(root_dir)),
                "columns": f"⚠️ Error: {e}"
            })
    return pd.DataFrame(csv_info)

# 📦 Run the scan
csv_columns_df = list_csv_columns(".")

# 🧾 Configure pandas to show all rows and columns
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", 200)

# 📊 Display the results
display(csv_columns_df)

# 💾 Optionally save to file
csv_columns_df.to_csv("csv_column_index.csv", index=False)
print("✅ Saved index as csv_column_index.csv")

,file,columns
0,node2vec_embeddings.csv,"[Neuron, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 4..."
1,nml_results.csv,"[FilePath, Tag, Attributes, Text, Pre, Post, Neuron, Source, Target]"
2,strength_metrics.csv,"[Neuron, TotalStrength, AvgRelatedness, StrengthImbalance]"
3,symbolic_clusters_labeled_canonical.csv,"[Neuron, Cluster, TSNE_1, TSNE_2, NeuronName, Canonical]"
4,ExtraData_Sheet_Classification.csv,"[Sheet, Rows, Cols, Columns, Classification]"
5,parsed_txt_salvaged.csv,"[**************************************************************************, __SourceFile, ADAL, Unnamed: 1, Unnamed: 2, Unnamed: 3, ADA, Unnamed: 5, Unnamed: 6, Unnamed: 7, in, I1, A 1 ..."
6,neuron_master.csv,"[Neuron, Type, TotalStrength, AvgRelatedness, StrengthImbalance, RichClubScore, total_3node_motifs, as_source, as_target, KMeansCluster, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1..."
7,motif_participation_profiles.csv,"[Neuron, (0, 1)_(0, 2)_(1, 2)_nan_nan_nan_nan_nan_nan, (0, 1)_(0, 2)_nan_nan_nan_nan_nan_nan_nan, (0, 1)_(2, 1)_nan_nan_nan_nan_nan_nan_nan, (0, 1)_(0, 2)_(2, 2)_nan_nan_nan_nan_nan_nan, (0, 1)_(0..."
8,latent_archetype_labels.csv,"[Unnamed: 0, AutoLabel]"
9,nca_symbolic_clusters.csv,"[Neuron, Cluster, TSNE_1, TSNE_2]"
10,parsed_txt_merged.csv,"[Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 1..."
11,parsed_txt_all.csv,"[Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 1..."
12,parsed_schema9_clean.csv,"[Col1, Col2, Col3, Col4, Col5, Col6, Col7, Col8, Col9, __SourceFile]"
13,cluster_feature_summary.csv,"[Leiden, TotalStrength, AvgRelatedness, StrengthImbalance, RichClubScore, total_3node_motifs, as_source, as_target, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22..."
14,symbolic_clusters_labeled_by_neuronname.csv,"[Neuron, Cluster, TSNE_1, TSNE_2, NeuronName, Canonical]"
15,normalized_schema9.csv,"[Neuron1, Neuron2, Count, __SourceFile]"
16,cluster_roles.csv,"[Leiden, LeidenRole]"
17,kmeans_cluster_roles.csv,"[Neuron, KMeansCluster]"
18,extradata_file_index.csv,"[RelativePath, Extension, Size_MB, Target]"
19,motif_null_trials.csv,"[trial, 003, 012, 102, 021D, 021U, 021C, 111D, 111U, 030T, 030C, 201, 120D, 120U, 120C, 210, 300]"
20,nca_symbolic_clusters_labeled.csv,"[Neuron, Cluster, TSNE_1, TSNE_2, NeuronName, SymbolicRole]"
21,neuron_motif_roles.csv,"[Neuron, Unclassified ❓]"
22,motif_global_counts_labeled.csv,"[MotifID, Count, Type]"
23,parsed_schema3_clean.csv,"[Col1, Col2, Col3, __SourceFile]"
24,out_synaptic_mechanisms.csv,"[FilePath, Tag, MechanismName, Params]"
25,nca_symbolic_clusters_with_names.csv,"[Neuron, Cluster, TSNE_1, TSNE_2, NeuronName]"
26,normalized_schema8.csv,"[Neuron, SegmentClass, Index1, Index2, Morphology, Flag1, Flag2, Flag3, __SourceFile]"
27,out_nml_parsed_elements.csv,"[FilePath, Tag, Attributes, Text]"
28,out_network_connections.csv,"[FilePath, Tag, Pre, Post, Weight]"
29,out_metadata_notes.csv,"[FilePath, Tag, Text]"
30,parsed_schema2_clean.csv,"[Col1, Col2, __SourceFile]"
31,out_morphology_segments.csv,"[FilePath, Neuron, Tag, x, y, z, diameter]"
32,extra_file_catalog.csv,"[FilePath, Extension, Size_MB, Preview, RelevanceScore]"
33,motif_class_table.csv,"[MotifID, Count, Edges, Class]"
34,motif_global_counts.csv,"[Unnamed: 0, Unnamed: 1, 0]"
35,parsed_schema8_clean.csv,"[Col1, Col2, Col3, Col4, Col5, Col6, Col7, Col8, __SourceFile]"
36,aconnectome_white_1986_whole.csv,[pre\tpost\ttype\tsynapses]
37,parsed_schema1_clean.csv,"[Col1, __SourceFile]"
38,motif_global_counts_cleaned.csv,"[MotifID, Count]"
39,wormbase_file_index.csv,"[RelativePath, Extension, Size_MB, Suggested_Target]"
40,parsed_txt_raw.csv,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5..."
41,richclub_scores.csv,"[Neuron, RichClubScore]"
42,phase1_results.csv,"[Unnamed: 0, Motif0, Motif1, Motif2, Motif3, Motif4, Motif5, Motif6, Motif7, Motif8, Motif9, Cluster, SymbolicRole, TotalSynapseCount]"
43,neuron_metadata.csv,"[Neuron, Type]"
44,tar_contents_catalog.csv,"[TarSource, FileName, FilePath, Extension, Size_KB]"
45,symbolic_cluster_type_enrichment.csv,"[Cluster, Interneuron, Motor, Sensory, Total, Sensory_%, Interneuron_%, Motor_%]"
46,motif_type_anova_results.csv,"[MotifClass, F-statistic, p-value]"
47,motif_scores.csv,"[Neuron, total_3node_motifs, as_source, as_target]"
48,motif_counts_with_structure.csv,"[MotifID, Count, Edges, Class, Structure]"
49,data/temp/Bentley_et_al_2016_expression.csv,"[Entity1, Relationship, Entity2, Evidence, Evidence URL]"
50,data/lineage/processed/merged_lineage_table.csv,"[NeuronA, NeuronB, Relatedness]"
51,data/connectivity/raw/aconnectome_white_1986_A.csv,[pre post type synapses]
52,data/connectivity/raw/aconnectome_white_1986_L4.csv,[pre\tpost\ttype\tsynapses]
53,data/connectivity/raw/herm_full_edgelist_MODIFIED.csv,"[Source, Target, Weight, Type]"
54,data/connectivity/raw/herm_full_edgelist.csv,"[Source, Target, Weight, Type]"
55,data/connectivity/processed/consensus_connectome_full_nofunc.csv,"[from_neuron, to_neuron, from_pos, to_pos, from_type, to_type, mean_gap_weight, mean_chem_weight, uncertainty, data_sources]"
56,data/connectivity/processed/merged_edges_with_relatedness.csv,"[Source, Target, Type, SynapseCount, SourceFile, Relatedness]"
57,data/connectivity/processed/consensus_connectome_full_withfunc.csv,"[from_neuron, to_neuron, from_pos, to_pos, from_type, to_type, mean_gap_weight, mean_chem_weight, uncertainty, functional_weight, data_sources]"
58,data/connectivity/processed/consensus_connectome_trimmed_nofunc.csv,"[from_neuron, to_neuron, from_pos, to_pos, from_type, to_type, mean_gap_weight, mean_chem_weight, uncertainty, data_sources]"
59,data/connectivity/processed/merged_edges.csv,"[Source, Target, Type, SynapseCount, SourceFile]"
60,data/connectivity/processed/consensus_connectome_trimmed_withfunc.csv,"[from_neuron, to_neuron, from_pos, to_pos, from_type, to_type, mean_gap_weight, mean_chem_weight, uncertainty, functional_weight, data_sources]"
61,data/exports/top_rich_motif_neurons.csv,"[Neuron, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, RichScore]"
62,data/metadata/file_index_master.csv,"[neuron, filename, full_path, extension, modality, directory]"
63,vgae_outputs/overnight_analysis/lesion_impact_ranking.csv,"[Unnamed: 0, neuron, clustering_impact, centrality_impact, motif_impact, type, symbolic_role, total_impact]"
64,vgae_outputs/overnight_analysis/motif_divergence.csv,"[Unnamed: 0, type, depth, kl_divergence]"
65,vgae_outputs/overnight_analysis/motif_enrichment.csv,"[Unnamed: 0, motif, depth, enrichment_pval, motif_count]"
66,utils/structured_data_inventory.csv,"[filename, full_path, size_kb, extension, data_type, num_rows, num_columns, column_names]"
67,utils/data_restructure_manifest_verified.csv,"[original_path, filename, canonical_path, category, notes, file_exists, basename, status]"
68,utils/final_verification_report.csv,"[original_path, filename, canonical_path, category, notes, file_exists, basename, status, relative_path, full_path, size_kb, _merge]"
69,utils/final_directory_context.csv,"[filename, relative_path, full_path, extension, size_kb]"
70,utils/data_validation_report.csv,"[basename, size_kb, status]"
71,utils/postmove_directory_inventory.csv,"[filename, relative_path, full_path, extension, size_kb]"
72,utils/data_restructure_manifest.csv,"[original_path, filename, canonical_path, category, notes]"

✅ Saved index as csv_column_index.csv

In [9]:
import pandas as pd

# Load uploaded CSV column index
csv_index = pd.read_csv("csv_column_index.csv")

# Convert stringified column lists back to Python lists if needed
import ast

def safe_parse_columns(x):
    try:
        parsed = ast.literal_eval(x)
        return parsed if isinstance(parsed, list) else [x]
    except Exception:
        return [x]

csv_index["columns"] = csv_index["columns"].apply(safe_parse_columns)
csv_index.head()

,file,columns
0,node2vec_embeddings.csv,"[Neuron, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 4..."
1,nml_results.csv,"[FilePath, Tag, Attributes, Text, Pre, Post, Neuron, Source, Target]"
2,strength_metrics.csv,"[Neuron, TotalStrength, AvgRelatedness, StrengthImbalance]"
3,symbolic_clusters_labeled_canonical.csv,"[Neuron, Cluster, TSNE_1, TSNE_2, NeuronName, Canonical]"
4,ExtraData_Sheet_Classification.csv,"[Sheet, Rows, Cols, Columns, Classification]"

In [10]:
# Create a stringified column signature
csv_index["schema_signature"] = csv_index["columns"].apply(lambda cols: str(sorted(cols)))

# Group by column signature
grouped = csv_index.groupby("schema_signature").agg({
    "file": list,
    "schema_signature": "count"
}).rename(columns={"schema_signature": "file_count"}).reset_index()

# Sort by most common schema
grouped.sort_values("file_count", ascending=False).head(10)

,schema_signature,file,file_count
66,['pre\tpost\ttype\tsynapses'],"[aconnectome_white_1986_whole.csv, data/connectivity/raw/aconnectome_white_1986_L4.csv]",2
64,"['extension', 'filename', 'full_path', 'relative_path', 'size_kb']","[utils/final_directory_context.csv, utils/postmove_directory_inventory.csv]",2
52,"['Source', 'Target', 'Type', 'Weight']","[data/connectivity/raw/herm_full_edgelist_MODIFIED.csv, data/connectivity/raw/herm_full_edgelist.csv]",2
62,"['data_sources', 'from_neuron', 'from_pos', 'from_type', 'mean_chem_weight', 'mean_gap_weight', 'to_neuron', 'to_pos', 'to_type', 'uncertainty']","[data/connectivity/processed/consensus_connectome_full_nofunc.csv, data/connectivity/processed/consensus_connectome_trimmed_nofunc.csv]",2
61,"['data_sources', 'from_neuron', 'from_pos', 'from_type', 'functional_weight', 'mean_chem_weight', 'mean_gap_weight', 'to_neuron', 'to_pos', 'to_type', 'uncertainty']","[data/connectivity/processed/consensus_connectome_full_withfunc.csv, data/connectivity/processed/consensus_connectome_trimmed_withfunc.csv]",2
15,"['Canonical', 'Cluster', 'Neuron', 'NeuronName', 'TSNE_1', 'TSNE_2']","[symbolic_clusters_labeled_canonical.csv, symbolic_clusters_labeled_by_neuronname.csv]",2
42,"['Flag1', 'Flag2', 'Flag3', 'Index1', 'Index2', 'Morphology', 'Neuron', 'SegmentClass', '__SourceFile']",[normalized_schema8.csv],1
46,"['Neuron', 'Type']",[neuron_metadata.csv],1
45,"['Neuron', 'RichClubScore']",[richclub_scores.csv],1
44,"['Leiden', 'LeidenRole']",[cluster_roles.csv],1

In [11]:
# Example: Show files with the most common schema
most_common_group = grouped.iloc[0]["file"]
print("📂 Files with most common schema:\n")
for f in most_common_group:
    print("•", f)

📂 Files with most common schema:

• parsed_txt_all.csv

In [12]:
import os
import shutil
from pathlib import Path

# 📂 Define where files should go
file_to_folder = {
    "node2vec_embeddings.csv":               "data/embeddings/",
    "symbolic_clusters_labeled_canonical.csv": "data/clustering/",
    "symbolic_clusters_labeled_by_neuronname.csv": "data/clustering/",
    "nml_results.csv":                        "data/results/",
    "ExtraData_Sheet_Classification.csv":     "data/results/",
    "strength_metrics.csv":                   "data/metrics/",
    "richclub_scores.csv":                    "data/metrics/",
    "cluster_roles.csv":                      "data/metrics/",
    "neuron_metadata.csv":                    "data/metadata/",
    "aconnectome_white_1986_whole.csv":       "data/connectivity/raw/",
    "aconnectome_white_1986_L4.csv":          "data/connectivity/raw/",
    "herm_full_edgelist.csv":                 "data/connectivity/raw/",
    "herm_full_edgelist_MODIFIED.csv":        "data/connectivity/raw/",
    "consensus_connectome_full_nofunc.csv":   "data/connectivity/processed/",
    "consensus_connectome_trimmed_nofunc.csv": "data/connectivity/processed/",
    "consensus_connectome_full_withfunc.csv": "data/connectivity/processed/",
    "consensus_connectome_trimmed_withfunc.csv": "data/connectivity/processed/",
    "final_directory_context.csv":            "data/utils/",
    "postmove_directory_inventory.csv":       "data/utils/",
    "parsed_txt_all.csv":                     "data/legacy_or_unknown/",
}

# 📁 Ensure all destination folders exist
for folder in set(file_to_folder.values()):
    Path(folder).mkdir(parents=True, exist_ok=True)
    # Add .gitkeep to keep empty folders in version control
    with open(Path(folder) / ".gitkeep", "w") as f:
        f.write("")

# 🚚 Move files into their folders
for filename, target_folder in file_to_folder.items():
    for path in Path(".").rglob(filename):
        dest = Path(target_folder) / path.name
        if not dest.exists():
            shutil.move(str(path), str(dest))
            print(f"📦 Moved {path} → {dest}")
        else:
            print(f"⚠️ Skipped (already exists): {path}")

print("✅ CSV reorganization complete.")

📦 Moved node2vec_embeddings.csv → data/embeddings/node2vec_embeddings.csv
⚠️ Skipped (already exists): data/embeddings/node2vec_embeddings.csv
📦 Moved symbolic_clusters_labeled_canonical.csv → data/clustering/symbolic_clusters_labeled_canonical.csv
⚠️ Skipped (already exists): data/clustering/symbolic_clusters_labeled_canonical.csv
📦 Moved symbolic_clusters_labeled_by_neuronname.csv → data/clustering/symbolic_clusters_labeled_by_neuronname.csv
⚠️ Skipped (already exists): data/clustering/symbolic_clusters_labeled_by_neuronname.csv
📦 Moved nml_results.csv → data/results/nml_results.csv
⚠️ Skipped (already exists): data/results/nml_results.csv
📦 Moved ExtraData_Sheet_Classification.csv → data/results/ExtraData_Sheet_Classification.csv
⚠️ Skipped (already exists): data/results/ExtraData_Sheet_Classification.csv
📦 Moved strength_metrics.csv → data/metrics/strength_metrics.csv
⚠️ Skipped (already exists): data/metrics/strength_metrics.csv
📦 Moved richclub_scores.csv → data/metrics/richclub_scores.csv
⚠️ Skipped (already exists): data/metrics/richclub_scores.csv
📦 Moved cluster_roles.csv → data/metrics/cluster_roles.csv
⚠️ Skipped (already exists): data/metrics/cluster_roles.csv
📦 Moved neuron_metadata.csv → data/metadata/neuron_metadata.csv
⚠️ Skipped (already exists): data/metadata/neuron_metadata.csv
📦 Moved aconnectome_white_1986_whole.csv → data/connectivity/raw/aconnectome_white_1986_whole.csv
⚠️ Skipped (already exists): data/connectivity/raw/aconnectome_white_1986_whole.csv
⚠️ Skipped (already exists): data/connectivity/raw/aconnectome_white_1986_L4.csv
⚠️ Skipped (already exists): data/connectivity/raw/herm_full_edgelist.csv
⚠️ Skipped (already exists): data/connectivity/raw/herm_full_edgelist_MODIFIED.csv
⚠️ Skipped (already exists): data/connectivity/processed/consensus_connectome_full_nofunc.csv
⚠️ Skipped (already exists): data/connectivity/processed/consensus_connectome_trimmed_nofunc.csv
⚠️ Skipped (already exists): data/connectivity/processed/consensus_connectome_full_withfunc.csv
⚠️ Skipped (already exists): data/connectivity/processed/consensus_connectome_trimmed_withfunc.csv
📦 Moved utils/final_directory_context.csv → data/utils/final_directory_context.csv
📦 Moved utils/postmove_directory_inventory.csv → data/utils/postmove_directory_inventory.csv
📦 Moved parsed_txt_all.csv → data/legacy_or_unknown/parsed_txt_all.csv
⚠️ Skipped (already exists): data/legacy_or_unknown/parsed_txt_all.csv
✅ CSV reorganization complete.

In [13]:
from pathlib import Path

def print_directory_structure(root_dir=".", show_files=True, max_depth=None):
    root = Path(root_dir).resolve()
    lines = []

    def walk(path, depth=0):
        if max_depth is not None and depth > max_depth:
            return
        indent = "    " * depth
        folder_name = path.name if depth > 0 else str(path)
        files = list(path.glob("*"))
        subdirs = [f for f in files if f.is_dir()]
        regular_files = [f for f in files if f.is_file()]

        lines.append(f"{indent}📁 {folder_name}/  ({len(regular_files)} files)")

        if show_files:
            for f in sorted(regular_files):
                lines.append(f"{indent}    📄 {f.name}")
        for d in sorted(subdirs):
            walk(d, depth + 1)

    walk(root)
    return "\n".join(lines)

# 📊 Run and output the full structure
layout_output = print_directory_structure(".", show_files=True)
print(layout_output)

# 💾 Optional: Save to file
with open("project_structure.txt", "w") as f:
    f.write(layout_output)

📁 /home/rohit/Desktop/Projects/C-Elegans/  (55 files)
    📄 .gitignore
    📄 automl_neuron.log
    📄 cleanup.ipynb
    📄 cluster_feature_summary.csv
    📄 csv_column_index.csv
    📄 datasetbuilder.ipynb
    📄 extra_file_catalog.csv
    📄 extradata_file_index.csv
    📄 kmeans_cluster_roles.csv
    📄 latent_archetype_labels.csv
    📄 lineageexploration.ipynb
    📄 motif_class_table.csv
    📄 motif_counts_with_structure.csv
    📄 motif_global_counts.csv
    📄 motif_global_counts_cleaned.csv
    📄 motif_global_counts_labeled.csv
    📄 motif_null_trials.csv
    📄 motif_participation_profiles.csv
    📄 motif_scores.csv
    📄 motif_type_anova_results.csv
    📄 motif_type_boxplot.png
    📄 nca_symbolic_clusters.csv
    📄 nca_symbolic_clusters_labeled.csv
    📄 nca_symbolic_clusters_with_names.csv
    📄 neuron_master.csv
    📄 neuron_motif_roles.csv
    📄 normalized_schema8.csv
    📄 normalized_schema9.csv
    📄 oscillator_neurons.txt
    📄 out_metadata_notes.csv
    📄 out_morphology_segments.csv
    📄 out_network_connections.csv
    📄 out_nml_parsed_elements.csv
    📄 out_synaptic_mechanisms.csv
    📄 output.txt
    📄 overnight2.ipynb
    📄 overnight_symbolic_pipeline.ipynb
    📄 parsed_schema1_clean.csv
    📄 parsed_schema2_clean.csv
    📄 parsed_schema3_clean.csv
    📄 parsed_schema8_clean.csv
    📄 parsed_schema9_clean.csv
    📄 parsed_txt_merged.csv
    📄 parsed_txt_raw.csv
    📄 parsed_txt_salvaged.csv
    📄 phase0.ipynb
    📄 phase1.ipynb
    📄 phase1.pdf
    📄 phase1_results.csv
    📄 roadmap.txt
    📄 symbolic_cluster_type_enrichment.csv
    📄 tar_contents_catalog.csv
    📄 top_motifs_table.tex
    📄 vgae_latents.pt
    📄 wormbase_file_index.csv
    📁 .git/  (5 files)
        📄 COMMIT_EDITMSG
        📄 HEAD
        📄 config
        📄 description
        📄 index
        📁 branches/  (0 files)
        📁 hooks/  (13 files)
            📄 applypatch-msg.sample
            📄 commit-msg.sample
            📄 fsmonitor-watchman.sample
            📄 post-update.sample
            📄 pre-applypatch.sample
            📄 pre-commit.sample
            📄 pre-merge-commit.sample
            📄 pre-push.sample
            📄 pre-rebase.sample
            📄 pre-receive.sample
            📄 prepare-commit-msg.sample
            📄 push-to-checkout.sample
            📄 update.sample
        📁 info/  (1 files)
            📄 exclude
        📁 logs/  (1 files)
            📄 HEAD
            📁 refs/  (0 files)
                📁 heads/  (1 files)
                    📄 main
                📁 remotes/  (0 files)
                    📁 origin/  (1 files)
                        📄 main
        📁 objects/  (0 files)
            📁 00/  (3 files)
                📄 7216fba880c4eaba2056e1eee03585796331ec
                📄 7423b3851976a6bb5287d02f50bb5534dd8294
                📄 fd5ba815576fac4ff163975f4eecddb21b6b44
            📁 01/  (4 files)
                📄 1c9732fb3ce8a10ea6eb9b996228c135616f22
                📄 4ec79c8615369845dbd5fadb0b87f668995935
                📄 5034721c5f598bbe0bc7c7e26b830f26a9eed7
                📄 b9cbe780d8f631fd321a64d7b60ea7eff6e3a3
            📁 02/  (3 files)
                📄 22970548ab065acb23c9e40f5c60774d406630
                📄 3a8675e7583b01ba27da0b509e7d29c52d3d7d
                📄 4ff0f3014963baaae3a4bb0a00829ba150ea08
            📁 03/  (4 files)
                📄 2c525a94da6f2ee602f1aba6e13b78c849d9c5
                📄 a8c632fe688cc1c0e4be3958c474443461c61a
                📄 b4e56643e47bf909572fefabd5d7c263ffaf46
                📄 d2c5543e53931b56a42ef69e62d8ea786beea1
            📁 04/  (2 files)
                📄 36265f6989b65bfdfd4ff4ab6a12f63026bde5
                📄 6caebfc8fd400035dbbfb6a84502538df89474
            📁 05/  (3 files)
                📄 20928cd4a8c5b968d368049130a10dc7d8d45e
                📄 cf860d84ab50868e7b5f0d8428f079e657d92c
                📄 d159518c45c9701cf054faf14eb1c3f04dd307
            📁 06/  (3 files)
                📄 1c002c911fee28275c76d70cb97198cf783b34
                📄 2e37aa0a774c2ba91d931c9af2f455dd4af67b
                📄 af7d0e905b11ea8f2d1219719b6eac692cae0b
            📁 07/  (4 files)
                📄 095df1deb0e2fa7b1e4e7588cdd9893b440777
                📄 178596738a409eef314f3c5ed61a6f09331909
                📄 22f475d718e429a762e298dc3909558d621712
                📄 c722571d176910d160d6f816a0b5bc8b3b44b1
            📁 09/  (1 files)
                📄 075782fc667a171c82be4fdb423ec362c5e73a
            📁 0a/  (2 files)
                📄 95df04124d50c5accf16dfb4edb4505dbd9130
                📄 971ede6d3c205acb5ca97ed0e35cfe56df1f5b
            📁 0b/  (3 files)
                📄 0326015df69534509989cd97fe6746b9e172b9
                📄 4bc083b30d8fcf1ad6fce4d3c186ac6cd7ee93
                📄 5546d6711fd119e45e835b095a0159a29e339f
            📁 0c/  (3 files)
                📄 64d6bb524d317897a6d68c435790b828da1c1c
                📄 b37eacbe59a1c0ee029b4b655abdfbc4e8fe81
                📄 cce9a2f45f24e29b487c4397ca2aefa4d0ee07
            📁 0e/  (3 files)
                📄 3a498a8da87e4aef8b94a0817748042d10b296
                📄 a66b135f3320730e8802d9d4d65f73bedb1471
                📄 cd9618f50e2c5c536bd99c5f3e0199f8559b6c
            📁 0f/  (2 files)
                📄 36bb3281fd526c853e8c02c0888a1a05647132
                📄 bc5a50d45df017ede846cda6d16fd74bdbfab6
            📁 10/  (1 files)
                📄 2059d164bca30c98f16786427e1e55ecef79da
            📁 12/  (3 files)
                📄 5b31a1d6492223a53457f42c884a39cdfc8e47
                📄 641d70ada7302454a2ee1fead7d99bb725b1b3
                📄 e4c36aa3a3fa7b671a9adefe6e44740f1267e0
            📁 13/  (3 files)
                📄 03afcf8c61ce358c7d042e01b8d1ff33f5b3bb
                📄 616a00cbffcead77ba9ccc75826bf9677d12d6
                📄 bd8ba2052e3fe3c6921c31403882d9c25dd246
            📁 14/  (2 files)
                📄 8aa32fcb6e7f2a623977793f2dcc2b8a48cda1
                📄 a0cc8b2b89bab6494a0e55c49aabf8cecd05c9
            📁 15/  (4 files)
                📄 4f5d1d28ad9833641db53a28fad1db6746c46d
                📄 577df82afdc9c842ae2a661bbd2ad55651dece
                📄 c066c4aa880f31858b7d38f1df51a4264a7b1a
                📄 d36d826945a2e21ef893b539e31350ebd14300
            📁 16/  (1 files)
                📄 8d2aa3f5c3e23fa502aea47a82dd29b51befa5
            📁 17/  (3 files)
                📄 880897b0dbdae597245a1b6a313c8e95bb6155
                📄 a12bf89ba7dd1b69eaa1b632d0dda984200e27
                📄 d8212100d016ad6bf5f297247c29c2498ecb00
            📁 18/  (2 files)
                📄 5ec908574d23031ac8a99d6fb4d83aa4bc161c
                📄 943aa0f5dad78fb6b64e1bcb4bb551107ac548
            📁 19/  (4 files)
                📄 88c6fe2bb082a748cc41cec0db0c31ac63ac6b
                📄 8ac6c23bd496733c10af99802df7b656397905
                📄 df7068df25ffb4a2e1acf532d8b197f929cbd0
                📄 efb6b27867beb56b8513d6528a94e5ebfc3fe0
            📁 1a/  (4 files)
                📄 6ebcfbae440d8cc08b89fe24f8fd87d1a7ef0d
                📄 927889c0e7379fa877574c3d8374b2e21b26f8
                📄 9443fd5aed9d41b9836c1a103f6dcf8292dd21
                📄 aa6ae5d033f7089ea21e8b0f1fe8b57385cf3d
            📁 1b/  (4 files)
                📄 3ca5f54ec13a779c0afcfa784eeb9082abb49a
                📄 4f8dc6474a05b33b8421dfaea165d85ef240c0
                📄 7f82fce174017d7f7505e08e835ba9c7b7c402
                📄 99d95f77550d4a282b4d5b66b2b9ca0b617637
            📁 1d/  (3 files)
                📄 27290d89eba324679a53f547ee8f0febc9a58f
                📄 f71c5a6e5f38421288e7447e4299c472c55bf9
                📄 ff4e6d33136550032576b7e42a9a845764ee46
            📁 1e/  (1 files)
                📄 389e817f183abda9a0262f326c843d578e787e
            📁 1f/  (7 files)
                📄 3be220271416c9c4ecfdd3c8a5aff5d1b3d384
                📄 45090ecaa7753d55b73c38b5ec74fb22c4a74d
                📄 4d603879d098dac0874b7c948b6e29980f1719
                📄 69481498b242caf4876b9d174d09d0ad53183d
                📄 8dd583fbc5ee57ecd82be48ee94946b02efa6d
                📄 c380f97a9588c7530463a9a221fabab82e3ab1
                📄 f72944bcef2efe183dfb972aa2f7bf41850e62
            📁 20/  (1 files)
                📄 5efca398cbbd18519da07b7b57305fe92faaf2
            📁 21/  (3 files)
                📄 55a7af65b9e286738993bdd26b532086e3fa34
                📄 67667b65f571f32f212da08f8c31c5de798d4c
                📄 c2c9446cab7706a2a3c6d51b96451b17003280
            📁 22/  (2 files)
                📄 8ba139fc3b75aca9729a845e014c448c6e5e8d
                📄 96913f08cf5a1e7e25dfd7851c561c3a4e3cda
            📁 23/  (6 files)
                📄 2838fa017a2afaefb27899059434778650a9ae
                📄 4586e472f4d3dab1be857a51975bca14d95792
                📄 724debf86e7c306ec1a8664065d02d68477706
                📄 d6f13e583f43f40e78a1c44cfce46df9b90ebf
                📄 ec8e6499be84c77ca4b15ae96e69e9fcf2a202
                📄 eec7429eda4030ac81a8e272d18da312c79d10
            📁 24/  (1 files)
                📄 d784ff06658369c7cafe5c90ac865e81f30ca1
            📁 25/  (4 files)
                📄 a27f41e2ccb8d3d608ae3bfb60ee6fa679f096
                📄 a32ebf3f929268cfe9e541e0fab12cca618e66
                📄 c0e2f5911c352ba02b40d9d46513e7b9b43ad8
                📄 e1574bb1f36efe602a5e74aa6b000ffcd46c7e
            📁 26/  (2 files)
                📄 a04b0343d895b38eda261983c98ceb707b8e54
                📄 bc41bf3cc0e3a10c22e21633e30ba3d482d6d1
            📁 27/  (5 files)
                📄 11f0ea7424330633925612729001223d4a13fc
                📄 9d45ca084c9ff71de2897db97c47c5b8b993c5
                📄 aa289e05d3fda14588c76a5bbf946d2b7c58f9
                📄 c00f7e58828ca24d5195e06f8a0af98d5c7c7e
                📄 c3f13888e6a3521111354936036be0c9cb70a4
            📁 28/  (1 files)
                📄 27efefb939b3319e4db33b90ae868813771162
            📁 29/  (2 files)
                📄 68be3543f07895ee66d837b3e2a2770090abb1
                📄 6b4e113715f919ada428aa68c1fb978a76d164
            📁 2a/  (4 files)
                📄 006bd7f33832e55687938fe71d7e0514bb779a
                📄 2794aace9776148693c90449ebf6a4578cc03f
                📄 351cb1a0270768a3977ab15b193b7fa305db52
                📄 a97b246827d02511dcf83593423087ae2e7eca
            📁 2b/  (4 files)
                📄 3138912011ee1240fa909e029a77c05659af13
                📄 33e9514486fbfd84e7c8285196474170c35080
                📄 6fbd739b77a64ee7c89d220e13e8c1746cb9a1
                📄 e8a0cf122b2805a9403b419aaad223e2dceb13
            📁 2c/  (4 files)
                📄 22dde8d05fb3626bff1677c024692f81ca05ee
                📄 26af69d7962ebd7c80792bc516302c07d35d89
                📄 73c5520821f83d9392ee561c1bc220e7b0c7f2
                📄 c718a2e632212618edc1e7bf168b401eb0bd59
            📁 2d/  (3 files)
                📄 17e6a9fc1946d121667dee3cde2e14bf0f6a37
                📄 51b0050762da4beefd50b526259bb9f12b8c51
                📄 a1837a22e0924e54e85d6b6bcc362abdcacb31
            📁 2e/  (4 files)
                📄 0e19dad8b4e6d79c98e67a42c99daaf5769c86
                📄 7c08d0badeedf9b98cf29542a75dfe734ed10c
                📄 92caa34950d30c1cb9b9c1b8e43dc1c601e2d0
                📄 aeaf2d3d3bdf3a6579b46a835f60399a989519
            📁 2f/  (5 files)
                📄 0cd9f8775ab28bcc1587c35a18bda5c4c6532f
                📄 71563bd7714725fcc46e80e8036e7d2f98a6dd
                📄 899578fcf57812fde86495cd1ac4fd1dcbebed
                📄 cb9aad679cdfc575430a825f539e39e0d68157
                📄 ddcc0d162c96445dac5d239709c6a5155f788e
            📁 30/  (5 files)
                📄 254e5a8c16a2c38f675bbb754d08b582d43d04
                📄 9135959847eaeaeed9d5676e7a3db3b234c16b
                📄 91da45b08c52e5f2ea72e24f6c418bfeaecb49
                📄 bb934dfbd1818d66c78bd52d9be7499dbf37b0
                📄 fc6294f2e46316c7febed129f34de349431ea6
            📁 31/  (2 files)
                📄 80ae02b4fec87b1323b524da70f4eebaa08d8b
                📄 d09e51fcfeed848905bc42439a11c41cf9f08c
            📁 32/  (2 files)
                📄 155895fdd9cdff982082d89636c107aad58ac2
                📄 af87a8e9144eef3cf0ab531f36ba020741bb54
            📁 33/  (1 files)
                📄 f652d232cdaa1a78925de3eba048707efa050f
            📁 34/  (2 files)
                📄 11f57ffe2f3f6c5edd3ea1cc2adcd6aa35b89e
                📄 19a59c31cdd1868510383bd0348eba7a0827a1
            📁 35/  (2 files)
                📄 7d700e0e4bd38301774e7b0dad751c66f4ced9
                📄 c5a65ecdc0b4261535dd23d914199db0c16b2f
            📁 36/  (2 files)
                📄 1c3b8433c28bfdf6289991449775da1561a6ad
                📄 fbb8f4dd001c3d304193af2725ebcdd01e083f
            📁 37/  (1 files)
                📄 f185f564adc68eaf0d6b9ff0ef756206cabb12
            📁 38/  (6 files)
                📄 007c242daa06fad7ed38603c6a977482ef15cc
                📄 39d150ddf72b011425b4b54bbbe1d53fa957a4
                📄 cbb78d789c794d537df7c0673a4b24c71b1f60
                📄 cfee9429275d9494b3e4cdf25c7e67a89e8ba8
                📄 defbe640ec03737fe931bf70d9a3e439305241
                📄 e699d0cb32cd879400d856cfaecc144c491b5f
            📁 3a/  (4 files)
                📄 13b514b6d3cedb21c569b92d1eacd104a5381e
                📄 473334302ba9867da212d18c588c140963665a
                📄 c165f885a1ee026c128b8d4af969df45de5d92
                📄 fc2a3ca4fe3ac35f8758c0206f9f5e3f52cd88
            📁 3b/  (4 files)
                📄 04a1b7090ccf322c80395687ecfc96068550ca
                📄 8a3352c0a96294c6dd16203b0cf572f7aacc9e
                📄 8a50c6b445531b9581a8f93db4aba931e0af0a
                📄 8e4b31942eb43b04034b37f23558430c6bb599
            📁 3c/  (4 files)
                📄 05ed8f75961e8dab9bf020ea66000f2443015a
                📄 86e47ba5b28805ae892259e49574d810e7e5c4
                📄 9e8db66d6f1f5f2b2368cdde3bde816f13ea45
                📄 e0adc67063c909f9a4430dc0e7b2fc51c8d37e
            📁 3d/  (3 files)
                📄 74de8963095b43f1f2ec0cfb64ec61c59f96bb
                📄 e8738f32875361a53ad06ff37bff7a3ca3231f
                📄 feb958c4e41a703419ee8072d985ef4726bb40
            📁 3e/  (3 files)
                📄 5b294fd8ff952f586badd7746f63f7df997b37
                📄 c9a1e2c78f6f8ee50ae5110da30e9f7d749923
                📄 eb805c2479b2e27e4cb4e504fb3a535ed23119
            📁 3f/  (5 files)
                📄 484361814e3e2198fbaf10c8cfc360667c4b71
                📄 4d99a1d6899fa3a43c1b9878f89d5ad20c549d
                📄 7a5cf5c8dee62d456a91f0993837733b24ca73
                📄 8af85b3b6895e8c39b01ec6f51b77172257b76
                📄 9ba1da097c39645e0151134110c058ea801509
            📁 40/  (2 files)
                📄 11e860a87f9299febd3fa62e3ca4eaeb8f6a78
                📄 18950c939ad7b1cddcb34f7a4fbd38d96ea72f
            📁 41/  (3 files)
                📄 227afc185e7039e2ef1d6fc37e4f89294527fa
                📄 48d3d29ec96088f8361cd44ae0dd349e3cba6d
                📄 7b3fcb38ad4e4290b7049f3edc74e94b4f733c
            📁 42/  (4 files)
                📄 02f328381b46e89841447d7480d94574bce22f
                📄 56f27f53265da12b28d06361d80c1bbf4e62e6
                📄 70ee53fbdd3bbcdd57a5c49a71a0dbe03c0b4d
                📄 a676e6059c726498ba1e083e0ade571447054d
            📁 43/  (1 files)
                📄 fddc66eae7b2f633aee87cc6667c6bb2e89245
            📁 44/  (2 files)
                📄 3fd50b752bca7cb8a304f3329492815fb1bff8
                📄 bb6852f08efac77c9f469870fbc519b9cbb370
            📁 46/  (3 files)
                📄 5955d3c4d7fe9fcdbbe3db8bc747b52d4f1c5d
                📄 af648d7b4aa42ee0efb4f65aebfa55bcf2f113
                📄 c370b9185dbce6fd0e8edd2dd59e8750edea55
            📁 47/  (4 files)
                📄 0a7425e6746d9a2786e000c0e0520804612ce0
                📄 839be14a860a6d1f790236c5952f83f9606dbd
                📄 b56270d57d0d4bd95cc4a04d4a6e5fe6fe6682
                📄 c68ca6aeba2eb63db27d112cd1baf7e2624a15
            📁 48/  (2 files)
                📄 b7829faeb6a991898ddcb248c92cf636e538cf
                📄 e6543a5f6c2a4bc37a1e39df18d7952fe20131
            📁 49/  (1 files)
                📄 69244b8bc7e16cef549655eaac24911ef12c9d
            📁 4a/  (3 files)
                📄 0cfeee8b7dfae82ee4884b1e0455b619f6ead5
                📄 2dc6a4879e8117af41c8bd02f60ee5014faaa6
                📄 bc3f5367698f7352701a8f56e12e684e534d1f
            📁 4b/  (6 files)
                📄 51232c66863141f862bbc49fcece9c6a8cf65d
                📄 568390b1663ad8c26ac9d5010f25b9d5ec89f2
                📄 780eeb8f6675027b93a879f16faad43b4db376
                📄 c9d95e271776c5c792c17d66c767511035f877
                📄 cf610a808eed8959a0c0949ae03347592060e4
                📄 fda671c3b290e17b156f79fe859d11e5f66b27
            📁 4c/  (6 files)
                📄 6788e3b86b612a964e70d4dee23fc79963454d
                📄 686289280bc719ee8e69189c065b85653d6319
                📄 74e4ffcf86f222817ad3f78443c7f53675a6b9
                📄 7e0721a220ee2dec92583845bf7676272828fe
                📄 8a8c17ffe903d20ee17565db510f14393e15ba
                📄 8e65c5088c184ab9bf534b01190f4bab3c82fd
            📁 4d/  (1 files)
                📄 3fc73fc22aef6f5a2d04ff25fa8564405e3714
            📁 4e/  (2 files)
                📄 b429c5edd2961f93b8a426449b73526933769e
                📄 e343957c1f4e5e8253dd6ef55785de65c86f98
            📁 4f/  (3 files)
                📄 3c971d79d72da218bc461178935cadcf58fc8b
                📄 87ee742ab917774556aa1666437f626a0e1252
                📄 d44f74d310194ad22026035207d9d3d94e1acd
            📁 50/  (4 files)
                📄 30333f92ba064f16696153779cbb165ed31e32
                📄 37c02b98f7f3077e19f5799fc6b4677b9be1b8
                📄 65baf77a58e990a28f460a1e4c1d6c5d2eecaf
                📄 f561fc158ebcd1f9796619f78a6d9321ee7575
            📁 51/  (4 files)
                📄 2a323ecf4acd4b808b26b23a83bec6c2ea01bc
                📄 318bfbf02f700dc54f7eb8d95c9deebb79334a
                📄 395bdedf800aab3bee702e62f4e18c06731c4b
                📄 ddeb989a2d8c415afa0f3e1d4d11494d7ed824
            📁 52/  (4 files)
                📄 2c13d9d61362bcd182fa2b4401aa07f27d82d8
                📄 90eefa3e48b1207f43351a8bd6766fb1995529
                📄 99d348eca01ea76313adbd3b866723b488245f
                📄 a020cc75e2c1d7b8f7ba9a7a5e56ea37382a08
            📁 53/  (3 files)
                📄 21ad806254926c8a065b1955b03ea7e29b575f
                📄 2ac6adf0dbc3221fda7db1688c5f278db8be01
                📄 f2c337ecfa07cd8dfaa8f24da96f7e1531339f
            📁 54/  (5 files)
                📄 076656eecabfc3602d1fee56188d8e5b75e789
                📄 11acc5db2ce3f0e0a21c45134d97e6267b5baf
                📄 1b1cf1abecd187dff0202a3a7fe35a86bdafe4
                📄 7d3f612e44cded4a1449dc4f91fbc5774fded5
                📄 e2b6bf38b9edcdfbd20285417f49efbb917b74
            📁 55/  (2 files)
                📄 80e7c8776e7bc88be5055b0735105d8bfb2798
                📄 b4d1b63fac6fef0a6653c71e0cf6d95d527125
            📁 57/  (2 files)
                📄 b5f2af10b30608ef29d0a3566bcfb305547f01
                📄 fb1e020187a60a06a71e5f943328249e0d8466
            📁 58/  (3 files)
                📄 25069aa2f2475b24596977bf44e2b49eba02a6
                📄 e1b0a44f70a704f55ff1b870ed559c942ecf25
                📄 e75d7051aaafe0669ae05c8a9c0f7da66022e3
            📁 59/  (1 files)
                📄 b2074b01179963629c3d53d31a7feb6f07e17d
            📁 5a/  (1 files)
                📄 dbbc0e79cc9dd1605365b2c56ce13c2d3f4d6f
            📁 5b/  (2 files)
                📄 11226c522fea9e44ea900f3f9d4275e359632b
                📄 d65f4fca0d1fcc3f79112448b124c97c06d3f2
            📁 5c/  (3 files)
                📄 195244ddce014c24f9846d84f55e1e32ca157c
                📄 2e169f9925f0b906ab0735f879e61b354bf7ee
                📄 a43f0809b8d2a2db87245d11610e6853790f87
            📁 5d/  (2 files)
                📄 5150b13c034702fd71a3b092bfe3d7ea3aa24d
                📄 d06484cff6abfd814bce6a8391fe12d0b8355c
            📁 5e/  (4 files)
                📄 4add19000dc32d51713f795fd4ccc4d4d7bd2b

In [14]:
from pathlib import Path
import shutil

# ─────────────────────────────────────────────────────────────
# 1) Define your buckets (destination folders)
# ─────────────────────────────────────────────────────────────
buckets = {
    # Code & notebooks
    "*.ipynb":   "notebooks/",
    "*.py":      "scripts/",
    # Logs, artifacts
    "*.log":     "logs/",
    "*.pdf":     "docs/",
    "*.tex":     "docs/",
    "*.txt":     "docs/",
    # Root-level CSVs (already cleaned): collect any leftovers
    "*.csv":     "data/root_csvs/",
    # Models
    "*.pt":      "models/",
    # Figures & images
    "*.png":     "figures/",
    "*.jpg":     "figures/",
    # WormBase/raw downloads
    "Downloads/":            "data/raw/wormbase_full_release/",
    "wormbase_full_release/": "data/raw/wormbase_full_release/",
    # Catch-all for HTML pages / listings
    "index.html*":           "trash/html_listings/",
}

# ─────────────────────────────────────────────────────────────
# 2) Create buckets & .gitkeep
# ─────────────────────────────────────────────────────────────
for dest in set(buckets.values()):
    dst = Path(dest)
    dst.mkdir(parents=True, exist_ok=True)
    # keep empty dirs in git
    (dst / ".gitkeep").write_text("")

# ─────────────────────────────────────────────────────────────
# 3) Move files / folders into the buckets
# ─────────────────────────────────────────────────────────────
root = Path(".").resolve()

for pattern, dest in buckets.items():
    # If pattern is a folder name, move that entire folder
    if root.joinpath(pattern).is_dir():
        src = root / pattern
        dst = root / dest / pattern
        if not dst.exists():
            shutil.move(str(src), str(dst))
            print(f"📂 Moved folder {src} → {dst}")
        continue

    # Otherwise treat it as a glob for files
    for path in root.rglob(pattern):
        # skip anything already in a bucket
        if Path(dest) in path.parents:
            continue
        dst = root / dest / path.name
        # avoid overwriting
        if dst.exists():
            print(f"⚠️ Skipped (exists): {path}")
        else:
            shutil.move(str(path), str(dst))
            print(f"📦 Moved {path} → {dst}")

# ─────────────────────────────────────────────────────────────
# 4) Final touches: collapse empty folders
# ─────────────────────────────────────────────────────────────
for d in root.rglob("*"):
    if d.is_dir() and not any(d.iterdir()):
        d.rmdir()
        print(f"🧹 Removed empty folder: {d}")

print("✅ Reorganization complete!")

📦 Moved /home/rohit/Desktop/Projects/C-Elegans/overnight2.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/overnight2.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/overnight_symbolic_pipeline.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/overnight_symbolic_pipeline.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/datasetbuilder.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/datasetbuilder.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/phase1.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/phase1.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/lineageexploration.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/lineageexploration.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/phase0.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/phase0.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/cleanup.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/cleanup.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/celegans.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/celegans.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/data/temp/phase0.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/connectome.ipynb → /home/rohit/Desktop/Projects/C-Elegans/notebooks/connectome.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/overnight2.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/overnight_symbolic_pipeline.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/datasetbuilder.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/phase1.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/celegans.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/lineageexploration.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/phase0.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/connectome.ipynb
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/notebooks/cleanup.ipynb
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Muscles.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Muscles.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/gen_graph.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/gen_graph.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_B.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_B.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/CheckProject.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/CheckProject.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/UpdatedSpreadsheetDataReader2.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/UpdatedSpreadsheetDataReader2.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/OpenWormReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/OpenWormReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/ConnectomeReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/ConnectomeReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Kato.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Kato.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_A_Weights.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_A_Weights.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_AWC.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_AWC.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/CompareMain.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/CompareMain.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/Sweep.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/Sweep.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_RIA.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_RIA.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Social.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Social.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_MultiSyns.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_MultiSyns.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/test_ex0_jnml.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex0_jnml.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_IClampMuscle.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_IClampMuscle.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_OscillatorM.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_OscillatorM.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/PositionStraighten.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/PositionStraighten.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/GenerateNeuroML.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/GenerateNeuroML.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/WormNeuroAtlasReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/WormNeuroAtlasReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Oscillator.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Oscillator.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/bioparameters.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/bioparameters.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/backers.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/backers.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_BC1.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_BC1.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/__version__.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/__version__.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/VarshneyDataReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/VarshneyDataReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_MusclesSine.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_MusclesSine.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/GenerateExamples.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/GenerateExamples.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/UpdatedSpreadsheetDataReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/UpdatedSpreadsheetDataReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/analyse.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/analyse.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_TargetMuscle.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_TargetMuscle.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_IClamp.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_IClamp.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Pharyngeal.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Pharyngeal.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_C2.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C2.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/test_ex_jnmlnrn.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex_jnmlnrn.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_A.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_A.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/SpreadsheetDataReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/SpreadsheetDataReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/printNML2Info.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/printNML2Info.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_utils.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_utils.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_C1.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C1.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/new_dataset_script.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/new_dataset_script.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Syns.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Syns.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_MuscleTest.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_MuscleTest.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/GABA.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/GABA.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_D.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_D.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/__init__.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/__init__.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_TapWithdrawal.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_TapWithdrawal.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/test_ex0_jnmlnrn.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex0_jnmlnrn.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_FW.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_FW.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/W_SpreadsheetDataReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/W_SpreadsheetDataReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/NeuroMLUtilities.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/NeuroMLUtilities.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_C.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/RegenerateConnectome.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/RegenerateConnectome.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/Generate.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/Generate.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/test_ex_jnml.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex_jnml.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/runAndPlot.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/runAndPlot.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_C0.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C0.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_W2D.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_W2D.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_info.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_info.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/parameters_D1.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_D1.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/Cook2019DataReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/Cook2019DataReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/c302_Full.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Full.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/White_A.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/White_A.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/White_L4.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/White_L4.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/Cook2019HermReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/Cook2019HermReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/White_whole.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/White_whole.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/WitvlietDataReader2.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/WitvlietDataReader2.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/WhiteDataReader.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/WhiteDataReader.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/connectivity/raw/WitvlietDataReader1.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/WitvlietDataReader1.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/neuroml/circuits/CanonicalCircuit.py → /home/rohit/Desktop/Projects/C-Elegans/scripts/CanonicalCircuit.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Muscles.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/gen_graph.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_B.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/CheckProject.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/UpdatedSpreadsheetDataReader2.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/OpenWormReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/ConnectomeReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Kato.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_A_Weights.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_AWC.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/CompareMain.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/Sweep.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/White_A.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/White_L4.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_RIA.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Social.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_MultiSyns.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex0_jnml.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_IClampMuscle.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/Cook2019HermReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_OscillatorM.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/PositionStraighten.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/GenerateNeuroML.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/WormNeuroAtlasReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Oscillator.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/bioparameters.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/White_whole.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/backers.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_BC1.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/__version__.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/VarshneyDataReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/WitvlietDataReader2.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_MusclesSine.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/GenerateExamples.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/UpdatedSpreadsheetDataReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/analyse.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_TargetMuscle.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_IClamp.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Pharyngeal.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C2.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/WhiteDataReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex_jnmlnrn.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_A.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/SpreadsheetDataReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/printNML2Info.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_utils.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C1.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/new_dataset_script.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Syns.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_MuscleTest.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/GABA.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_D.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/__init__.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_TapWithdrawal.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex0_jnmlnrn.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_FW.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/W_SpreadsheetDataReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/NeuroMLUtilities.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/RegenerateConnectome.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/Generate.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/test_ex_jnml.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/runAndPlot.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_C0.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_W2D.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_info.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/parameters_D1.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/Cook2019DataReader.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/CanonicalCircuit.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/c302_Full.py
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/scripts/WitvlietDataReader1.py
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/automl_neuron.log → /home/rohit/Desktop/Projects/C-Elegans/logs/automl_neuron.log
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/logs/connectome_pipeline_20250807_205553.log
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/logs/automl_neuron.log
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/logs/connectome_pipeline_20250807_210120.log
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/vgae_outputs/logs/connectome_pipeline_20250807_210017.log → /home/rohit/Desktop/Projects/C-Elegans/logs/connectome_pipeline_20250807_210017.log
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/phase1.pdf → /home/rohit/Desktop/Projects/C-Elegans/docs/phase1.pdf
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/connectome.pdf → /home/rohit/Desktop/Projects/C-Elegans/docs/connectome.pdf
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/data/temp/celegans.pdf → /home/rohit/Desktop/Projects/C-Elegans/docs/celegans.pdf
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/docs/connectome.pdf
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/docs/phase1.pdf
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/docs/celegans.pdf
📦 Moved /home/rohit/Desktop/Projects/C-Elegans/top_motifs_table.tex → /home/rohit/Desktop/Projects/C-Elegans/docs/top_motifs_table.tex
⚠️ Skipped (exists): /home/rohit/Desktop/Projects/C-Elegans/docs/top_motifs_table.tex

Error: Cannot move a directory '/home/rohit/Desktop/Projects/C-Elegans/data/raw/wormbase_full_release' into itself '/home/rohit/Desktop/Projects/C-Elegans/data/raw/wormbase_full_release/wormbase_full_release'.

In [15]:
print_directory_structure(".", show_files=False)

'📁 /home/rohit/Desktop/Projects/C-Elegans/  (1 files)\n    📁 .git/  (5 files)\n        📁 branches/  (0 files)\n        📁 hooks/  (13 files)\n        📁 info/  (1 files)\n        📁 logs/  (1 files)\n            📁 refs/  (0 files)\n                📁 heads/  (1 files)\n                📁 remotes/  (0 files)\n                    📁 origin/  (1 files)\n        📁 objects/  (0 files)\n            📁 00/  (3 files)\n            📁 01/  (4 files)\n            📁 02/  (3 files)\n            📁 03/  (4 files)\n            📁 04/  (2 files)\n            📁 05/  (3 files)\n            📁 06/  (3 files)\n            📁 07/  (4 files)\n            📁 09/  (1 files)\n            📁 0a/  (2 files)\n            📁 0b/  (3 files)\n            📁 0c/  (3 files)\n            📁 0e/  (3 files)\n            📁 0f/  (2 files)\n            📁 10/  (1 files)\n            📁 12/  (3 files)\n            📁 13/  (3 files)\n            📁 14/  (2 files)\n            📁 15/  (4 files)\n            📁 16/  (1 files)\n            📁 17/  (3 files)\n            📁 18/  (2 files)\n            📁 19/  (4 files)\n            📁 1a/  (4 files)\n            📁 1b/  (4 files)\n            📁 1d/  (3 files)\n            📁 1e/  (1 files)\n            📁 1f/  (7 files)\n            📁 20/  (1 files)\n            📁 21/  (3 files)\n            📁 22/  (2 files)\n            📁 23/  (6 files)\n            📁 24/  (1 files)\n            📁 25/  (4 files)\n            📁 26/  (2 files)\n            📁 27/  (5 files)\n            📁 28/  (1 files)\n            📁 29/  (2 files)\n            📁 2a/  (4 files)\n            📁 2b/  (4 files)\n            📁 2c/  (4 files)\n            📁 2d/  (3 files)\n            📁 2e/  (4 files)\n            📁 2f/  (5 files)\n            📁 30/  (5 files)\n            📁 31/  (2 files)\n            📁 32/  (2 files)\n            📁 33/  (1 files)\n            📁 34/  (2 files)\n            📁 35/  (2 files)\n            📁 36/  (2 files)\n            📁 37/  (1 files)\n            📁 38/  (6 files)\n            📁 3a/  (4 files)\n            📁 3b/  (4 files)\n            📁 3c/  (4 files)\n            📁 3d/  (3 files)\n            📁 3e/  (3 files)\n            📁 3f/  (5 files)\n            📁 40/  (2 files)\n            📁 41/  (3 files)\n            📁 42/  (4 files)\n            📁 43/  (1 files)\n            📁 44/  (2 files)\n            📁 46/  (3 files)\n            📁 47/  (4 files)\n            📁 48/  (2 files)\n            📁 49/  (1 files)\n            📁 4a/  (3 files)\n            📁 4b/  (6 files)\n            📁 4c/  (6 files)\n            📁 4d/  (1 files)\n            📁 4e/  (2 files)\n            📁 4f/  (3 files)\n            📁 50/  (4 files)\n            📁 51/  (4 files)\n            📁 52/  (4 files)\n            📁 53/  (3 files)\n            📁 54/  (5 files)\n            📁 55/  (2 files)\n            📁 57/  (2 files)\n            📁 58/  (3 files)\n            📁 59/  (1 files)\n            📁 5a/  (1 files)\n            📁 5b/  (2 files)\n            📁 5c/  (3 files)\n            📁 5d/  (2 files)\n            📁 5e/  (4 files)\n            📁 60/  (2 files)\n            📁 61/  (1 files)\n            📁 62/  (3 files)\n            📁 63/  (4 files)\n            📁 64/  (1 files)\n            📁 65/  (4 files)\n            📁 66/  (5 files)\n            📁 67/  (1 files)\n            📁 68/  (4 files)\n            📁 69/  (3 files)\n            📁 6a/  (8 files)\n            📁 6b/  (2 files)\n            📁 6c/  (7 files)\n            📁 6d/  (3 files)\n            📁 6e/  (2 files)\n            📁 70/  (2 files)\n            📁 71/  (3 files)\n            📁 72/  (2 files)\n            📁 73/  (3 files)\n            📁 74/  (6 files)\n            📁 75/  (2 files)\n            📁 76/  (3 files)\n            📁 77/  (5 files)\n            📁 78/  (2 files)\n            📁 79/  (5 files)\n            📁 7a/  (3 files)\n            📁 7b/  (4 files)\n            📁 7c/  (2 files)\n            📁 7d/  (1 files)\n            📁 7e/  (1 files)\n            📁 7f/  (4 files)\n            📁 80/  (6 files)\n            📁 81/  (5 files)\n            📁 82/  (2 files)\n            📁 83/  (5 files)\n            📁 84/  (2 files)\n            📁 86/  (1 files)\n            📁 87/  (3 files)\n            📁 88/  (3 files)\n            📁 89/  (3 files)\n            📁 8a/  (4 files)\n            📁 8b/  (6 files)\n            📁 8c/  (5 files)\n            📁 8d/  (4 files)\n            📁 8e/  (2 files)\n            📁 8f/  (7 files)\n            📁 90/  (5 files)\n            📁 91/  (4 files)\n            📁 92/  (5 files)\n            📁 93/  (4 files)\n            📁 94/  (2 files)\n            📁 95/  (1 files)\n            📁 96/  (2 files)\n            📁 97/  (5 files)\n            📁 98/  (2 files)\n            📁 99/  (7 files)\n            📁 9a/  (4 files)\n            📁 9b/  (1 files)\n            📁 9c/  (4 files)\n            📁 9d/  (2 files)\n            📁 9e/  (5 files)\n            📁 9f/  (3 files)\n            📁 a0/  (1 files)\n            📁 a1/  (3 files)\n            📁 a2/  (3 files)\n            📁 a4/  (4 files)\n            📁 a5/  (2 files)\n            📁 a7/  (4 files)\n            📁 a8/  (4 files)\n            📁 a9/  (4 files)\n            📁 aa/  (4 files)\n            📁 ab/  (1 files)\n            📁 ac/  (4 files)\n            📁 ad/  (2 files)\n            📁 ae/  (4 files)\n            📁 b0/  (6 files)\n            📁 b1/  (4 files)\n            📁 b2/  (1 files)\n            📁 b3/  (1 files)\n            📁 b4/  (1 files)\n            📁 b5/  (7 files)\n            📁 b6/  (2 files)\n            📁 b7/  (2 files)\n            📁 b8/  (7 files)\n            📁 b9/  (5 files)\n            📁 ba/  (2 files)\n            📁 bb/  (3 files)\n            📁 bc/  (3 files)\n            📁 bd/  (5 files)\n            📁 be/  (8 files)\n            📁 bf/  (3 files)\n            📁 c0/  (2 files)\n            📁 c1/  (4 files)\n            📁 c2/  (3 files)\n            📁 c3/  (4 files)\n            📁 c4/  (3 files)\n            📁 c5/  (4 files)\n            📁 c6/  (4 files)\n            📁 c7/  (7 files)\n            📁 c8/  (2 files)\n            📁 c9/  (6 files)\n            📁 ca/  (3 files)\n            📁 cb/  (2 files)\n            📁 cc/  (4 files)\n            📁 cd/  (5 files)\n            📁 ce/  (2 files)\n            📁 d0/  (1 files)\n            📁 d1/  (2 files)\n            📁 d2/  (5 files)\n            📁 d3/  (5 files)\n            📁 d4/  (5 files)\n            📁 d5/  (3 files)\n            📁 d6/  (4 files)\n            📁 d7/  (1 files)\n            📁 d8/  (3 files)\n            📁 d9/  (4 files)\n            📁 da/  (2 files)\n            📁 db/  (4 files)\n            📁 dc/  (2 files)\n            📁 dd/  (3 files)\n            📁 de/  (4 files)\n            📁 df/  (4 files)\n            📁 e0/  (4 files)\n            📁 e1/  (5 files)\n            📁 e2/  (3 files)\n            📁 e3/  (3 files)\n            📁 e4/  (3 files)\n            📁 e5/  (3 files)\n            📁 e6/  (3 files)\n            📁 e7/  (1 files)\n            📁 e8/  (1 files)\n            📁 e9/  (4 files)\n            📁 ea/  (3 files)\n            📁 eb/  (8 files)\n            📁 ec/  (4 files)\n            📁 ed/  (2 files)\n            📁 ee/  (3 files)\n            📁 ef/  (4 files)\n            📁 f1/  (2 files)\n            📁 f2/  (1 files)\n            📁 f3/  (6 files)\n            📁 f4/  (5 files)\n            📁 f5/  (2 files)\n            📁 f6/  (4 files)\n            📁 f7/  (1 files)\n            📁 f8/  (4 files)\n            📁 f9/  (2 files)\n            📁 fa/  (6 files)\n            📁 fb/  (3 files)\n            📁 fc/  (1 files)\n            📁 fd/  (1 files)\n            📁 fe/  (6 files)\n            📁 ff/  (2 files)\n            📁 info/  (0 files)\n            📁 pack/  (0 files)\n        📁 refs/  (0 files)\n            📁 heads/  (1 files)\n            📁 remotes/  (0 files)\n                📁 origin/  (1 files)\n            📁 tags/  (0 files)\n    📁 ExtraData/  (19 files)\n    📁 ExtractedFiles/  (0 files)\n        📁 brenneri_cDNAs_WS245/  (0 files)\n        📁 brenneri_cDNAs_WS250/  (0 files)\n        📁 brenneri_cDNAs_WS255/  (0 files)\n        📁 brenneri_cDNAs_WS260/  (0 files)\n        📁 brenneri_cDNAs_WS265/  (0 files)\n        📁 brenneri_cDNAs_WS270/  (0 files)\n        📁 brenneri_cDNAs_WS297/  (0 files)\n        📁 brenneri_genes_WS245/  (0 files)\n        📁 brenneri_genes_WS250/  (0 files)\n        📁 brenneri_genes_WS255/  (0 files)\n        📁 brenneri_genes_WS260/  (0 files)\n        📁 brenneri_genes_WS265/  (0 files)\n        📁 brenneri_genes_WS270/  (0 files)\n        📁 brenneri_genes_WS297/  (0 files)\n        📁 brenneri_ncRNAs_WS245/  (0 files)\n        📁 brenneri_ncRNAs_WS250/  (0 files)\n        📁 brenneri_ncRNAs_WS255/  (0 files)\n        📁 brenneri_ncRNAs_WS260/  (0 files)\n        📁 brenneri_ncRNAs_WS265/  (0 files)\n        📁 brenneri_ncRNAs_WS270/  (0 files)\n        📁 brenneri_ncRNAs_WS297/  (0 files)\n        📁 brenneri_pseudogenes_WS245/  (0 files)\n        📁 brenneri_pseudogenes_WS250/  (0 files)\n        📁 brenneri_pseudogenes_WS255/  (0 files)\n        📁 brenneri_pseudogenes_WS260/  (0 files)\n        📁 brenneri_pseudogenes_WS265/  (0 files)\n        📁 brenneri_pseudogenes_WS270/  (0 files)\n        📁 brenneri_pseudogenes_WS297/  (0 files)\n        📁 brenneri_repeatmasker/  (0 files)\n        📁 briggsae_cDNAs_WS245/  (0 files)\n        📁 briggsae_cDNAs_WS250/  (0 files)\n        📁 briggsae_cDNAs_WS255/  (0 files)\n        📁 briggsae_cDNAs_WS260/  (0 files)\n        📁 briggsae_cDNAs_WS265/  (0 files)\n        📁 briggsae_cDNAs_WS270/  (0 files)\n        📁 briggsae_cDNAs_WS297/  (0 files)\n        📁 briggsae_genes_WS245/  (0 files)\n        📁 briggsae_genes_WS250/  (0 files)\n        📁 briggsae_genes_WS255/  (0 files)\n        📁 briggsae_genes_WS260/  (0 files)\n        📁 briggsae_genes_WS265/  (0 files)\n        📁 briggsae_genes_WS270/  (0 files)\n        📁 briggsae_genes_WS297/  (0 files)\n        📁 briggsae_ncRNAs_WS245/  (0 files)\n        📁 briggsae_ncRNAs_WS250/  (0 files)\n        📁 briggsae_ncRNAs_WS255/  (0 files)\n        📁 briggsae_ncRNAs_WS260/  (0 files)\n        📁 briggsae_ncRNAs_WS265/  (0 files)\n        📁 briggsae_ncRNAs_WS270/  (0 files)\n        📁 briggsae_ncRNAs_WS297/  (0 files)\n        📁 briggsae_pseudogenes_WS245/  (0 files)\n        📁 briggsae_pseudogenes_WS250/  (0 files)\n        📁 briggsae_pseudogenes_WS255/  (0 files)\n        📁 briggsae_pseudogenes_WS260/  (0 files)\n        📁 briggsae_pseudogenes_WS265/  (0 files)\n        📁 briggsae_pseudogenes_WS270/  (0 files)\n        📁 briggsae_pseudogenes_WS297/  (0 files)\n        📁 briggsae_repeatmasker/  (0 files)\n        📁 brugia_cDNAs_WS245/  (0 files)\n        📁 brugia_cDNAs_WS250/  (0 files)\n        📁 brugia_cDNAs_WS255/  (0 files)\n        📁 brugia_cDNAs_WS260/  (0 files)\n        📁 brugia_cDNAs_WS265/  (0 files)\n        📁 brugia_cDNAs_WS270/  (0 files)\n        📁 brugia_cDNAs_WS297/  (0 files)\n        📁 brugia_genes_WS245/  (0 files)\n        📁 brugia_genes_WS250/  (0 files)\n        📁 brugia_genes_WS255/  (0 files)\n        📁 brugia_genes_WS260/  (0 files)\n        📁 brugia_genes_WS265/  (0 files)\n        📁 brugia_genes_WS270/  (0 files)\n        📁 brugia_genes_WS297/  (0 files)\n        📁 brugia_ncRNAs_WS245/  (0 files)\n        📁 brugia_ncRNAs_WS250/  (0 files)\n        📁 brugia_ncRNAs_WS255/  (0 files)\n        📁 brugia_ncRNAs_WS260/  (0 files)\n        📁 brugia_ncRNAs_WS265/  (0 files)\n        📁 brugia_ncRNAs_WS270/  (0 files)\n        📁 brugia_ncRNAs_WS297/  (0 files)\n        📁 brugia_pseudogenes_WS245/  (0 files)\n        📁 brugia_pseudogenes_WS250/  (0 files)\n        📁 brugia_pseudogenes_WS255/  (0 files)\n        📁 brugia_pseudogenes_WS260/  (0 files)\n        📁 brugia_pseudogenes_WS265/  (0 files)\n        📁 brugia_pseudogenes_WS270/  (0 files)\n        📁 brugia_pseudogenes_WS297/  (0 files)\n        📁 brugia_repeatmasker/  (0 files)\n        📁 c_nigoni_genes_WS264/  (0 files)\n        📁 elegans_cDNAs_WS245/  (0 files)\n        📁 elegans_cDNAs_WS250/  (0 files)\n        📁 elegans_cDNAs_WS255/  (0 files)\n        📁 elegans_cDNAs_WS260/  (0 files)\n        📁 elegans_cDNAs_WS265/  (0 files)\n        📁 elegans_cDNAs_WS270/  (0 files)\n        📁 elegans_cDNAs_WS297/  (0 files)\n        📁 elegans_genes_WS245/  (0 files)\n        📁 elegans_genes_WS250/  (0 files)\n        📁 elegans_genes_WS255/  (0 files)\n        📁 elegans_genes_WS260/  (0 files)\n        📁 elegans_genes_WS265/  (0 files)\n        📁 elegans_genes_WS270/  (0 files)\n        📁 elegans_genes_WS297/  (0 files)\n        📁 elegans_ncRNAs_WS245/  (0 files)\n        📁 elegans_ncRNAs_WS250/  (0 files)\n        📁 elegans_ncRNAs_WS255/  (0 files)\n        📁 elegans_ncRNAs_WS260/  (0 files)\n        📁 elegans_ncRNAs_WS265/  (0 files)\n        📁 elegans_ncRNAs_WS270/  (0 files)\n        📁 elegans_ncRNAs_WS297/  (0 files)\n        📁 elegans_pseudogenes_WS245/  (0 files)\n        📁 elegans_pseudogenes_WS250/  (0 files)\n        📁 elegans_pseudogenes_WS255/  (0 files)\n        📁 elegans_pseudogenes_WS260/  (0 files)\n        📁 elegans_pseudogenes_WS265/  (0 files)\n        📁 elegans_pseudogenes_WS270/  (0 files)\n        📁 elegans_pseudogenes_WS297/  (0 files)\n        📁 elegans_repeatmasker/  (0 files)\n        📁 japonica_cDNAs_WS245/  (0 files)\n        📁 japonica_cDNAs_WS250/  (0 files)\n        📁 japonica_cDNAs_WS255/  (0 files)\n        📁 japonica_cDNAs_WS260/  (0 files)\n        📁 japonica_cDNAs_WS265/  (0 files)\n        📁 japonica_cDNAs_WS270/  (0 files)\n        📁 japonica_cDNAs_WS297/  (0 files)\n        📁 japonica_genes_WS245/  (0 files)\n        📁 japonica_genes_WS250/  (0 files)\n        📁 japonica_genes_WS255/  (0 files)\n        📁 japonica_genes_WS260/  (0 files)\n        📁 japonica_genes_WS265/  (0 files)\n        📁 japonica_genes_WS270/  (0 files)\n        📁 japonica_genes_WS297/  (0 files)\n        📁 japonica_ncRNAs_WS245/  (0 files)\n        📁 japonica_ncRNAs_WS250/  (0 files)\n        📁 japonica_ncRNAs_WS255/  (0 files)\n        📁 japonica_ncRNAs_WS260/  (0 files)\n        📁 japonica_ncRNAs_WS265/  (0 files)\n        📁 japonica_ncRNAs_WS270/  (0 files)\n        📁 japonica_ncRNAs_WS297/  (0 files)\n        📁 japonica_pseudogenes_WS245/  (0 files)\n        📁 japonica_pseudogenes_WS250/  (0 files)\n        📁 japonica_pseudogenes_WS255/  (0 files)\n        📁 japonica_pseudogenes_WS260/  (0 files)\n        📁 japonica_pseudogenes_WS265/  (0 files)\n        📁 japonica_pseudogenes_WS270/  (0 files)\n        📁 japonica_pseudogenes_WS297/  (0 files)\n        📁 japonica_repeatmasker/  (0 files)\n        📁 ovolvulus_cDNAs_WS245/  (0 files)\n        📁 ovolvulus_cDNAs_WS250/  (0 files)\n        📁 ovolvulus_cDNAs_WS255/  (0 files)\n        📁 ovolvulus_cDNAs_WS260/  (0 files)\n        📁 ovolvulus_cDNAs_WS265/  (0 files)\n        📁 ovolvulus_cDNAs_WS270/  (0 files)\n        📁 ovolvulus_cDNAs_WS297/  (0 files)\n        📁 ovolvulus_genes_WS245/  (0 files)\n        📁 ovolvulus_genes_WS250/  (0 files)\n        📁 ovolvulus_genes_WS255/  (0 files)\n        📁 ovolvulus_genes_WS260/  (0 files)\n        📁 ovolvulus_genes_WS265/  (0 files)\n        📁 ovolvulus_genes_WS270/  (0 files)\n        📁 ovolvulus_genes_WS297/  (0 files)\n        📁 ovolvulus_ncRNAs_WS245/  (0 files)\n        📁 ovolvulus_ncRNAs_WS250/  (0 files)\n        📁 ovolvulus_ncRNAs_WS255/  (0 files)\n        📁 ovolvulus_ncRNAs_WS260/  (0 files)\n        📁 ovolvulus_ncRNAs_WS265/  (0 files)\n        📁 ovolvulus_ncRNAs_WS270/  (0 files)\n        📁 ovolvulus_ncRNAs_WS297/  (0 files)\n        📁 ovolvulus_pseudogenes_WS245/  (0 files)\n        📁 ovolvulus_pseudogenes_WS250/  (0 files)\n        📁 ovolvulus_pseudogenes_WS255/  (0 files)\n        📁 ovolvulus_pseudogenes_WS260/  (0 files)\n        📁 ovolvulus_pseudogenes_WS265/  (0 files)\n        📁 ovolvulus_pseudogenes_WS270/  (0 files)\n        📁 ovolvulus_pseudogenes_WS297/  (0 files)\n        📁 ovolvulus_repeatmasker/  (0 files)\n        📁 pristionchus_cDNAs_WS265/  (0 files)\n        📁 pristionchus_cDNAs_WS270/  (0 files)\n        📁 pristionchus_cDNAs_WS297/  (0 files)\n        📁 pristionchus_genes_WS265/  (0 files)\n        📁 pristionchus_genes_WS270/  (0 files)\n        📁 pristionchus_genes_WS297/  (0 files)\n        📁 pristionchus_pseudogenes_WS297/  (0 files)\n        📁 remanei_cDNAs_WS244/  (0 files)\n        📁 remanei_cDNAs_WS247/  (0 files)\n        📁 remanei_cDNAs_WS250/  (0 files)\n        📁 remanei_cDNAs_WS255/  (0 files)\n        📁 remanei_cDNAs_WS260/  (0 files)\n        📁 remanei_cDNAs_WS265/  (0 files)\n        📁 remanei_cDNAs_WS270/  (0 files)\n        📁 remanei_cDNAs_WS297/  (0 files)\n        📁 remanei_genes_WS244/  (0 files)\n        📁 remanei_genes_WS247/  (0 files)\n        📁 remanei_genes_WS250/  (0 files)\n        📁 remanei_genes_WS255/  (0 files)\n        📁 remanei_genes_WS260/  (0 files)\n        📁 remanei_genes_WS265/  (0 files)\n        📁 remanei_genes_WS270/  (0 files)\n        📁 remanei_genes_WS297/  (0 files)\n        📁 remanei_ncRNAs_WS244/  (0 files)\n        📁 remanei_ncRNAs_WS247/  (0 files)\n        📁 remanei_ncRNAs_WS250/  (0 files)\n        📁 remanei_ncRNAs_WS255/  (0 files)\n        📁 remanei_ncRNAs_WS260/  (0 files)\n        📁 remanei_ncRNAs_WS265/  (0 files)\n        📁 remanei_ncRNAs_WS270/  (0 files)\n        📁 remanei_ncRNAs_WS297/  (0 files)\n        📁 remanei_pseudogenes_WS244/  (0 files)\n        📁 remanei_pseudogenes_WS247/  (0 files)\n        📁 remanei_pseudogenes_WS250/  (0 files)\n        📁 remanei_pseudogenes_WS255/  (0 files)\n        📁 remanei_pseudogenes_WS260/  (0 files)\n        📁 remanei_pseudogenes_WS265/  (0 files)\n        📁 remanei_pseudogenes_WS270/  (0 files)\n        📁 remanei_pseudogenes_WS297/  (0 files)\n        📁 remanei_repeatmasker/  (0 files)\n        📁 s_ratti_cDNAs_WS250/  (0 files)\n        📁 s_ratti_cDNAs_WS255/  (0 files)\n        📁 s_ratti_cDNAs_WS265/  (0 files)\n        📁 s_ratti_cDNAs_WS270/  (0 files)\n        📁 s_ratti_cDNAs_WS297/  (0 files)\n        📁 s_ratti_genes_WS250/  (0 files)\n        📁 s_ratti_genes_WS255/  (0 files)\n        📁 s_ratti_genes_WS265/  (0 files)\n        📁 s_ratti_genes_WS270/  (0 files)\n        📁 s_ratti_genes_WS297/  (0 files)\n        📁 s_ratti_ncRNAs_WS255/  (0 files)\n        📁 s_ratti_ncRNAs_WS265/  (0 files)\n        📁 s_ratti_ncRNAs_WS270/  (0 files)\n        📁 s_ratti_ncRNAs_WS297/  (0 files)\n        📁 s_ratti_repeatmasker/  (0 files)\n        📁 t_muris_cDNAs_WS265/  (0 files)\n        📁 t_muris_cDNAs_WS270/  (0 files)\n        📁 t_muris_cDNAs_WS297/  (0 files)\n        📁 t_muris_genes_WS265/  (0 files)\n        📁 t_muris_genes_WS270/  (0 files)\n        📁 t_muris_genes_WS297/  (0 files)\n        📁 t_muris_ncRNAs_WS265/  (0 files)\n        📁 t_muris_ncRNAs_WS270/  (0 files)\n        📁 t_muris_ncRNAs_WS297/  (0 files)\n        📁 ws268/  (0 files)\n        📁 ws268_lod_1274/  (0 files)\n        📁 ws268_lod_203/  (0 files)\n        📁 ws268_lod_32/  (0 files)\n        📁 ws268_lod_509/  (0 files)\n        📁 ws268_lod_81/  (0 files)\n    📁 Unpacked/  (1 files)\n        📁 database_297_4-10_tar/  (0 files)\n            📁 database/  (4 files)\n        📁 database_297_4-15_tar/  (0 files)\n            📁 database/  (5 files)\n        📁 database_297_4-17_tar/  (0 files)\n            📁 database/  (2 files)\n        📁 database_297_4-1_tar/  (0 files)\n            📁 database/  (5 files)\n        📁 database_297_4-2_tar/  (0 files)\n            📁 database/  (5 files)\n        📁 database_297_4-6_tar/  (0 files)\n            📁 database/  (5 files)\n    📁 _extracted_tars/  (0 files)\n        📁 database.297.4-0/  (0 files)\n            📁 database/  (3 files)\n            📁 wgf/  (14 files)\n            📁 wquery/  (138 files)\n                📁 geneace/  (33 files)\n                    📁 REMOVED/  (30 files)\n            📁 wspec/  (13 files)\n        📁 database.297.4-1/  (0 files)\n            📁 database/  (5 files)\n        📁 database.297.4-10/  (0 files)\n            📁 database/  (5 files)\n        📁 database.297.4-11/  (0 files)\n            📁 database/  (1 files)\n        📁 database.297.4-12/  (0 files)\n      

In [16]:
import os

def print_tree(root, prefix=""):
    """
    Recursively prints a directory tree.

    root   : path to the directory you want to list
    prefix : used internally for drawing the tree branches
    """
    try:
        entries = sorted(os.listdir(root))
    except PermissionError:
        return

    for idx, name in enumerate(entries):
        path = os.path.join(root, name)
        # choose branch or end-of-branch connector
        connector = "└── " if idx == len(entries) - 1 else "├── "
        print(prefix + connector + name)

        if os.path.isdir(path):
            # adjust the prefix for children
            extension = "    " if idx == len(entries) - 1 else "│   "
            print_tree(path, prefix + extension)

# ── CONFIGURE HERE ───────────────────────────────────────────────────────────
PROJECT_ROOT = "/home/rohit/Desktop/C-Elegans"
# ─────────────────────────────────────────────────────────────────────────────

print(PROJECT_ROOT)
print_tree(PROJECT_ROOT)

/home/rohit/Desktop/Projects/C-Elegans
├── .git
│   ├── COMMIT_EDITMSG
│   ├── HEAD
│   ├── branches
│   ├── config
│   ├── description
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── push-to-checkout.sample
│   │   └── update.sample
│   ├── index
│   ├── info
│   │   └── exclude
│   ├── logs
│   │   ├── HEAD
│   │   └── refs
│   │       ├── heads
│   │       │   └── main
│   │       └── remotes
│   │           └── origin
│   │               └── main
│   ├── objects
│   │   ├── 00
│   │   │   ├── 7216fba880c4eaba2056e1eee03585796331ec
│   │   │   ├── 7423b3851976a6bb5287d02f50bb5534dd8294
│   │   │   └── fd5ba815576fac4ff163975f4eecddb21b6b44
│   │   ├── 01
│   │   │   ├── 1c9732fb3ce8a10ea6eb9b996228c135616f22
│   │   │   ├── 4ec79c8615369845dbd5fadb0b87f668995935
│   │   │   ├── 5034721c5f598bbe0bc7c7e26b830f26a9eed7
│   │   │   └── b9cbe780d8f631fd321a64d7b60ea7eff6e3a3
│   │   ├── 02
│   │   │   ├── 22970548ab065acb23c9e40f5c60774d406630
│   │   │   ├── 3a8675e7583b01ba27da0b509e7d29c52d3d7d
│   │   │   └── 4ff0f3014963baaae3a4bb0a00829ba150ea08
│   │   ├── 03
│   │   │   ├── 2c525a94da6f2ee602f1aba6e13b78c849d9c5
│   │   │   ├── a8c632fe688cc1c0e4be3958c474443461c61a
│   │   │   ├── b4e56643e47bf909572fefabd5d7c263ffaf46
│   │   │   └── d2c5543e53931b56a42ef69e62d8ea786beea1
│   │   ├── 04
│   │   │   ├── 36265f6989b65bfdfd4ff4ab6a12f63026bde5
│   │   │   └── 6caebfc8fd400035dbbfb6a84502538df89474
│   │   ├── 05
│   │   │   ├── 20928cd4a8c5b968d368049130a10dc7d8d45e
│   │   │   ├── cf860d84ab50868e7b5f0d8428f079e657d92c
│   │   │   └── d159518c45c9701cf054faf14eb1c3f04dd307
│   │   ├── 06
│   │   │   ├── 1c002c911fee28275c76d70cb97198cf783b34
│   │   │   ├── 2e37aa0a774c2ba91d931c9af2f455dd4af67b
│   │   │   └── af7d0e905b11ea8f2d1219719b6eac692cae0b
│   │   ├── 07
│   │   │   ├── 095df1deb0e2fa7b1e4e7588cdd9893b440777
│   │   │   ├── 178596738a409eef314f3c5ed61a6f09331909
│   │   │   ├── 22f475d718e429a762e298dc3909558d621712
│   │   │   └── c722571d176910d160d6f816a0b5bc8b3b44b1
│   │   ├── 09
│   │   │   └── 075782fc667a171c82be4fdb423ec362c5e73a
│   │   ├── 0a
│   │   │   ├── 95df04124d50c5accf16dfb4edb4505dbd9130
│   │   │   └── 971ede6d3c205acb5ca97ed0e35cfe56df1f5b
│   │   ├── 0b
│   │   │   ├── 0326015df69534509989cd97fe6746b9e172b9
│   │   │   ├── 4bc083b30d8fcf1ad6fce4d3c186ac6cd7ee93
│   │   │   └── 5546d6711fd119e45e835b095a0159a29e339f
│   │   ├── 0c
│   │   │   ├── 64d6bb524d317897a6d68c435790b828da1c1c
│   │   │   ├── b37eacbe59a1c0ee029b4b655abdfbc4e8fe81
│   │   │   └── cce9a2f45f24e29b487c4397ca2aefa4d0ee07
│   │   ├── 0e
│   │   │   ├── 3a498a8da87e4aef8b94a0817748042d10b296
│   │   │   ├── a66b135f3320730e8802d9d4d65f73bedb1471
│   │   │   └── cd9618f50e2c5c536bd99c5f3e0199f8559b6c
│   │   ├── 0f
│   │   │   ├── 36bb3281fd526c853e8c02c0888a1a05647132
│   │   │   └── bc5a50d45df017ede846cda6d16fd74bdbfab6
│   │   ├── 10
│   │   │   └── 2059d164bca30c98f16786427e1e55ecef79da
│   │   ├── 12
│   │   │   ├── 5b31a1d6492223a53457f42c884a39cdfc8e47
│   │   │   ├── 641d70ada7302454a2ee1fead7d99bb725b1b3
│   │   │   └── e4c36aa3a3fa7b671a9adefe6e44740f1267e0
│   │   ├── 13
│   │   │   ├── 03afcf8c61ce358c7d042e01b8d1ff33f5b3bb
│   │   │   ├── 616a00cbffcead77ba9ccc75826bf9677d12d6
│   │   │   └── bd8ba2052e3fe3c6921c31403882d9c25dd246
│   │   ├── 14
│   │   │   ├── 8aa32fcb6e7f2a623977793f2dcc2b8a48cda1
│   │   │   └── a0cc8b2b89bab6494a0e55c49aabf8cecd05c9
│   │   ├── 15
│   │   │   ├── 4f5d1d28ad9833641db53a28fad1db6746c46d
│   │   │   ├── 577df82afdc9c842ae2a661bbd2ad55651dece
│   │   │   ├── c066c4aa880f31858b7d38f1df51a4264a7b1a
│   │   │   └── d36d826945a2e21ef893b539e31350ebd14300
│   │   ├── 16
│   │   │   └── 8d2aa3f5c3e23fa502aea47a82dd29b51befa5
│   │   ├── 17
│   │   │   ├── 880897b0dbdae597245a1b6a313c8e95bb6155
│   │   │   ├── a12bf89ba7dd1b69eaa1b632d0dda984200e27
│   │   │   └── d8212100d016ad6bf5f297247c29c2498ecb00
│   │   ├── 18
│   │   │   ├── 5ec908574d23031ac8a99d6fb4d83aa4bc161c
│   │   │   └── 943aa0f5dad78fb6b64e1bcb4bb551107ac548
│   │   ├── 19
│   │   │   ├── 88c6fe2bb082a748cc41cec0db0c31ac63ac6b
│   │   │   ├── 8ac6c23bd496733c10af99802df7b656397905
│   │   │   ├── df7068df25ffb4a2e1acf532d8b197f929cbd0
│   │   │   └── efb6b27867beb56b8513d6528a94e5ebfc3fe0
│   │   ├── 1a
│   │   │   ├── 6ebcfbae440d8cc08b89fe24f8fd87d1a7ef0d
│   │   │   ├── 927889c0e7379fa877574c3d8374b2e21b26f8
│   │   │   ├── 9443fd5aed9d41b9836c1a103f6dcf8292dd21
│   │   │   └── aa6ae5d033f7089ea21e8b0f1fe8b57385cf3d
│   │   ├── 1b
│   │   │   ├── 3ca5f54ec13a779c0afcfa784eeb9082abb49a
│   │   │   ├── 4f8dc6474a05b33b8421dfaea165d85ef240c0
│   │   │   ├── 7f82fce174017d7f7505e08e835ba9c7b7c402
│   │   │   └── 99d95f77550d4a282b4d5b66b2b9ca0b617637
│   │   ├── 1d
│   │   │   ├── 27290d89eba324679a53f547ee8f0febc9a58f
│   │   │   ├── f71c5a6e5f38421288e7447e4299c472c55bf9
│   │   │   └── ff4e6d33136550032576b7e42a9a845764ee46
│   │   ├── 1e
│   │   │   └── 389e817f183abda9a0262f326c843d578e787e
│   │   ├── 1f
│   │   │   ├── 3be220271416c9c4ecfdd3c8a5aff5d1b3d384
│   │   │   ├── 45090ecaa7753d55b73c38b5ec74fb22c4a74d
│   │   │   ├── 4d603879d098dac0874b7c948b6e29980f1719
│   │   │   ├── 69481498b242caf4876b9d174d09d0ad53183d
│   │   │   ├── 8dd583fbc5ee57ecd82be48ee94946b02efa6d
│   │   │   ├── c380f97a9588c7530463a9a221fabab82e3ab1
│   │   │   └── f72944bcef2efe183dfb972aa2f7bf41850e62
│   │   ├── 20
│   │   │   └── 5efca398cbbd18519da07b7b57305fe92faaf2
│   │   ├── 21
│   │   │   ├── 55a7af65b9e286738993bdd26b532086e3fa34
│   │   │   ├── 67667b65f571f32f212da08f8c31c5de798d4c
│   │   │   └── c2c9446cab7706a2a3c6d51b96451b17003280
│   │   ├── 22
│   │   │   ├── 8ba139fc3b75aca9729a845e014c448c6e5e8d
│   │   │   └── 96913f08cf5a1e7e25dfd7851c561c3a4e3cda
│   │   ├── 23
│   │   │   ├── 2838fa017a2afaefb27899059434778650a9ae
│   │   │   ├── 4586e472f4d3dab1be857a51975bca14d95792
│   │   │   ├── 724debf86e7c306ec1a8664065d02d68477706
│   │   │   ├── d6f13e583f43f40e78a1c44cfce46df9b90ebf
│   │   │   ├── ec8e6499be84c77ca4b15ae96e69e9fcf2a202
│   │   │   └── eec7429eda4030ac81a8e272d18da312c79d10
│   │   ├── 24
│   │   │   └── d784ff06658369c7cafe5c90ac865e81f30ca1
│   │   ├── 25
│   │   │   ├── a27f41e2ccb8d3d608ae3bfb60ee6fa679f096
│   │   │   ├── a32ebf3f929268cfe9e541e0fab12cca618e66
│   │   │   ├── c0e2f5911c352ba02b40d9d46513e7b9b43ad8
│   │   │   └── e1574bb1f36efe602a5e74aa6b000ffcd46c7e
│   │   ├── 26
│   │   │   ├── a04b0343d895b38eda261983c98ceb707b8e54
│   │   │   └── bc41bf3cc0e3a10c22e21633e30ba3d482d6d1
│   │   ├── 27
│   │   │   ├── 11f0ea7424330633925612729001223d4a13fc
│   │   │   ├── 9d45ca084c9ff71de2897db97c47c5b8b993c5
│   │   │   ├── aa289e05d3fda14588c76a5bbf946d2b7c58f9
│   │   │   ├── c00f7e58828ca24d5195e06f8a0af98d5c7c7e
│   │   │   └── c3f13888e6a3521111354936036be0c9cb70a4
│   │   ├── 28
│   │   │   └── 27efefb939b3319e4db33b90ae868813771162
│   │   ├── 29
│   │   │   ├── 68be3543f07895ee66d837b3e2a2770090abb1
│   │   │   └── 6b4e113715f919ada428aa68c1fb978a76d164
│   │   ├── 2a
│   │   │   ├── 006bd7f33832e55687938fe71d7e0514bb779a
│   │   │   ├── 2794aace9776148693c90449ebf6a4578cc03f
│   │   │   ├── 351cb1a0270768a3977ab15b193b7fa305db52
│   │   │   └── a97b246827d02511dcf83593423087ae2e7eca
│   │   ├── 2b
│   │   │   ├── 3138912011ee1240fa909e029a77c05659af13
│   │   │   ├── 33e9514486fbfd84e7c8285196474170c35080
│   │   │   ├── 6fbd739b77a64ee7c89d220e13e8c1746cb9a1
│   │   │   └── e8a0cf122b2805a9403b419aaad223e2dceb13
│   │   ├── 2c
│   │   │   ├── 22dde8d05fb3626bff1677c024692f81ca05ee
│   │   │   ├── 26af69d7962ebd7c80792bc516302c07d35d89
│   │   │   ├── 73c5520821f83d9392ee561c1bc220e7b0c7f2
│   │   │   └── c718a2e632212618edc1e7bf168b401eb0bd59
│   │   ├── 2d
│   │   │   ├── 17e6a9fc1946d121667dee3cde2e14bf0f6a37
│   │   │   ├── 51b0050762da4beefd50b526259bb9f12b8c51
│   │   │   └── a1837a22e0924e54e85d6b6bcc362abdcacb31
│   │   ├── 2e
│   │   │   ├── 0e19dad8b4e6d79c98e67a42c99daaf5769c86
│   │   │   ├── 7c08d0badeedf9b98cf29542a75dfe734ed10c
│   │   │   ├── 92caa34950d30c1cb9b9c1b8e43dc1c601e2d0
│   │   │   └── aeaf2d3d3bdf3a6579b46a835f60399a989519
│   │   ├── 2f
│   │   │   ├── 0cd9f8775ab28bcc1587c35a18bda5c4c6532f
│   │   │   ├── 71563bd7714725fcc46e80e8036e7d2f98a6dd
│   │   │   ├── 899578fcf57812fde86495cd1ac4fd1dcbebed
│   │   │   ├── cb9aad679cdfc575430a825f539e39e0d68157
│   │   │   └── ddcc0d162c96445dac5d239709c6a5155f788e
│   │   ├── 30
│   │   │   ├── 254e5a8c16a2c38f675bbb754d08b582d43d04
│   │   │   ├── 9135959847eaeaeed9d5676e7a3db3b234c16b
│   │   │   ├── 91da45b08c52e5f2ea72e24f6c418bfeaecb49
│   │   │   ├── bb934dfbd1818d66c78bd52d9be7499dbf37b0
│   │   │   └── fc6294f2e46316c7febed129f34de349431ea6
│   │   ├── 31
│   │   │   ├── 80ae02b4fec87b1323b524da70f4eebaa08d8b
│   │   │   └── d09e51fcfeed848905bc42439a11c41cf9f08c
│   │   ├── 32
│   │   │   ├── 155895fdd9cdff982082d89636c107aad58ac2
│   │   │   └── af87a8e9144eef3cf0ab531f36ba020741bb54
│   │   ├── 33
│   │   │   └── f652d232cdaa1a78925de3eba048707efa050f
│   │   ├── 34
│   │   │   ├── 11f57ffe2f3f6c5edd3ea1cc2adcd6aa35b89e
│   │   │   └── 19a59c31cdd1868510383bd0348eba7a0827a1
│   │   ├── 35
│   │   │   ├── 7d700e0e4bd38301774e7b0dad751c66f4ced9
│   │   │   └── c5a65ecdc0b4261535dd23d914199db0c16b2f
│   │   ├── 36
│   │   │   ├── 1c3b8433c28bfdf6289991449775da1561a6ad
│   │   │   └── fbb8f4dd001c3d304193af2725ebcdd01e083f
│   │   ├── 37
│   │   │   └── f185f564adc68eaf0d6b9ff0ef756206cabb12
│   │   ├── 38
│   │   │   ├── 007c242daa06fad7ed38603c6a977482ef15cc
│   │   │   ├── 39d150ddf72b011425b4b54bbbe1d53fa957a4
│   │   │   ├── cbb78d789c794d537df7c0673a4b24c71b1f60
│   │   │   ├── cfee9429275d9494b3e4cdf25c7e67a89e8ba8
│   │   │   ├── defbe640ec03737fe931bf70d9a3e439305241
│   │   │   └── e699d0cb32cd879400d856cfaecc144c491b5f
│   │   ├── 3a
│   │   │   ├── 13b514b6d3cedb21c569b92d1eacd104a5381e
│   │   │   ├── 473334302ba9867da212d18c588c140963665a
│   │   │   ├── c165f885a1ee026c128b8d4af969df45de5d92
│   │   │   └── fc2a3ca4fe3ac35f8758c0206f9f5e3f52cd88
│   │   ├── 3b
│   │   │   ├── 04a1b7090ccf322c80395687ecfc96068550ca
│   │   │   ├── 8a3352c0a96294c6dd16203b0cf572f7aacc9e
│   │   │   ├── 8a50c6b445531b9581a8f93db4aba931e0af0a
│   │   │   └── 8e4b31942eb43b04034b37f23558430c6bb599
│   │   ├── 3c
│   │   │   ├── 05ed8f75961e8dab9bf020ea66000f2443015a
│   │   │   ├── 86e47ba5b28805ae892259e49574d810e7e5c4
│   │   │   ├── 9e8db66d6f1f5f2b2368cdde3bde816f13ea45
│   │   │   └── e0adc67063c909f9a4430dc0e7b2fc51c8d37e
│   │   ├── 3d
│   │   │   ├── 74de8963095b43f1f2ec0cfb64ec61c59f96bb
│   │   │   ├── e8738f32875361a53ad06ff37bff7a3ca3231f
│   │   │   └── feb958c4e41a703419ee8072d985ef4726bb40
│   │   ├── 3e
│   │   │   ├── 5b294fd8ff952f586badd7746f63f7df997b37
│   │   │   ├── c9a1e2c78f6f8ee50ae5110da30e9f7d749923
│   │   │   └── eb805c2479b2e27e4cb4e504fb3a535ed23119
│   │   ├── 3f
│   │   │   ├── 484361814e3e2198fbaf10c8cfc360667c4b71
│   │   │   ├── 4d99a1d6899fa3a43c1b9878f89d5ad20c549d
│   │   │   ├── 7a5cf5c8dee62d456a91f0993837733b24ca73
│   │   │   ├── 8af85b3b6895e8c39b01ec6f51b77172257b76
│   │   │   └── 9ba1da097c39645e0151134110c058ea801509
│   │   ├── 40
│   │   │   ├── 11e860a87f9299febd3fa62e3ca4eaeb8f6a78
│   │   │   └── 18950c939ad7b1cddcb34f7a4fbd38d96ea72f
│   │   ├── 41
│   │   │   ├── 227afc185e7039e2ef1d6fc37e4f89294527fa
│   │   │   ├── 48d3d29ec96088f8361cd44ae0dd349e3cba6d
│   │   │   └── 7b3fcb38ad4e4290b7049f3edc74e94b4f733c
│   │   ├── 42
│   │   │   ├── 02f328381b46e89841447d7480d94574bce22f
│   │   │   ├── 56f27f53265da12b28d06361d80c1bbf4e62e6
│   │   │   ├── 70ee53fbdd3bbcdd57a5c49a71a0dbe03c0b4d
│   │   │   └── a676e6059c726498ba1e083e0ade571447054d
│   │   ├── 43
│   │   │   └── fddc66eae7b2f633aee87cc6667c6bb2e89245
│   │   ├── 44
│   │   │   ├── 3fd50b752bca7cb8a304f3329492815fb1bff8
│   │   │   └── bb6852f08efac77c9f469870fbc519b9cbb370
│   │   ├── 46
│   │   │   ├── 5955d3c4d7fe9fcdbbe3db8bc747b52d4f1c5d
│   │   │   ├── af648d7b4aa42ee0efb4f65aebfa55bcf2f113
│   │   │   └── c370b9185dbce6fd0e8edd2dd59e8750edea55
│   │   ├── 47
│   │   │   ├── 0a7425e6746d9a2786e000c0e0520804612ce0
│   │   │   ├── 839be14a860a6d1f790236c5952f83f9606dbd
│   │   │   ├── b56270d57d0d4bd95cc4a04d4a6e5fe6fe6682
│   │   │   └── c68ca6aeba2eb63db27d112cd1baf7e2624a15
│   │   ├── 48
│   │   │   ├── b7829faeb6a991898ddcb248c92cf636e538cf
│   │   │   └── e6543a5f6c2a4bc37a1e39df18d7952fe20131
│   │   ├── 49
│   │   │   └── 69244b8bc7e16cef549655eaac24911ef12c9d
│   │   ├── 4a
│   │   │   ├── 0cfeee8b7dfae82ee4884b1e0455b619f6ead5
│   │   │   ├── 2dc6a4879e8117af41c8bd02f60ee5014faaa6
│   │   │   └── bc3f5367698f7352701a8f56e12e684e534d1f
│   │   ├── 4b
│   │   │   ├── 51232c66863141f862bbc49fcece9c6a8cf65d
│   │   │   ├── 568390b1663ad8c26ac9d5010f25b9d5ec89f2
│   │   │   ├── 780eeb8f6675027b93a879f16faad43b4db376
│   │   │   ├── c9d95e271776c5c792c17d66c767511035f877
│   │   │   ├── cf610a808eed8959a0c0949ae03347592060e4
│   │   │   └── fda671c3b290e17b156f79fe859d11e5f66b27
│   │   ├── 4c
│   │   │   ├── 6788e3b86b612a964e70d4dee23fc79963454d
│   │   │   ├── 686289280bc719ee8e69189c065b85653d6319
│   │   │   ├── 74e4ffcf86f222817ad3f78443c7f53675a6b9
│   │   │   ├── 7e0721a220ee2dec92583845bf7676272828fe
│   │   │   ├── 8a8c17ffe903d20ee17565db510f14393e15ba
│   │   │   └── 8e65c5088c184ab9bf534b01190f4bab3c82fd
│   │   ├── 4d
│   │   │   └── 3fc73fc22aef6f5a2d04ff25fa8564405e3714
│   │   ├── 4e
│   │   │   ├── b429c5edd2961f93b8a426449b73526933769e
│   │   │   └── e343957c1f4e5e8253dd6ef55785de65c86f98
│   │   ├── 4f
│   │   │   ├── 3c971d79d72da218bc461178935cadcf58fc8b
│   │   │   ├── 87ee742ab917774556aa1666437f626a0e1252
│   │   │   └── d44f74d310194ad22026035207d9d3d94e1acd
│   │   ├── 50
│   │   │   ├── 30333f92ba064f16696153779cbb165ed31e32
│   │   │   ├── 37c02b98f7f3077e19f5799fc6b4677b9be1b8
│   │   │   ├── 65baf77a58e990a28f460a1e4c1d6c5d2eecaf
│   │   │   └── f561fc158ebcd1f9796619f78a6d9321ee7575
│   │   ├── 51
│   │   │   ├── 2a323ecf4acd4b808b26b23a83bec6c2ea01bc
│   │   │   ├── 318bfbf02f700dc54f7eb8d95c9deebb79334a
│   │   │   ├── 395bdedf800aab3bee702e62f4e18c06731c4b
│   │   │   └── ddeb989a2d8c415afa0f3e1d4d11494d7ed824
│   │   ├── 52
│   │   │   ├── 2c13d9d61362bcd182fa2b4401aa07f27d82d8
│   │   │   ├── 90eefa3e48b1207f43351a8bd6766fb1995529
│   │   │   ├── 99d348eca01ea76313adbd3b866723b488245f
│   │   │   └── a020cc75e2c1d7b8f7ba9a7a5e56ea37382a08
│   │   ├── 53
│   │   │   ├── 21ad806254926c8a065b1955b03ea7e29b575f
│   │   │   ├── 2ac6adf0dbc3221fda7db1688c5f278db8be01
│   │   │   └── f2c337ecfa07cd8dfaa8f24da96f7e1531339f
│   │   ├── 54
│   │   │   ├── 076656eecabfc3602d1fee56188d8e5b75e789
│   │   │   ├── 11acc5db2ce3f0e0a21c45134d97e6267b5baf
│   │   │   ├── 1b1cf1abecd187dff0202a3a7fe35a86bdafe4
│   │   │   ├── 7d3f612e44cded4a1449dc4f91fbc5774fded5
│   │   │   └── e2b6bf38b9edcdfbd20285417f49efbb917b74
│   │   ├── 55
│   │   │   ├── 80e7c8776e7bc88be5055b0735105d8bfb2798
│   │   │   └── b4d1b63fac6fef0a6653c71e0cf6d95d527125
│   │   ├── 57
│   │   │   ├── b5f2af10b30608ef29d0a3566bcfb305547f01
│   │   │   └── fb1e020187a60a06a71e5f943328249e0d8466
│   │   ├── 58
│   │   │   ├── 25069aa2f2475b24596977bf44e2b49eba02a6
│   │   │   ├── e1b0a44f70a704f55ff1b870ed559c942ecf25
│   │   │   └── e75d7051aaafe0669ae05c8a9c0f7da66022e3
│   │   ├── 59
│   │   │   └── b2074b01179963629c3d53d31a7feb6f07e17d
│   │   ├── 5a
│   │   │   └── dbbc0e79cc9dd1605365b2c56ce13c2d3f4d6f
│   │   ├── 5b
│   │   │   ├── 11226c522fea9e44ea900f3f9d4275e359632b
│   │   │   └── d65f4fca0d1fcc3f79112448b124c97c06d3f2
│   │   ├── 5c
│   │   │   ├── 195244ddce014c24f9846d84f55e1e32ca157c
│   │   │   ├── 2e169f9925f0b906ab0735f879e61b354bf7ee
│   │   │   └── a43f0809b8d2a2db87245d11610e6853790f87
│   │   ├── 5d
│   │   │   ├── 5150b13c034702fd71a3b092bfe3d7ea3aa24d
│   │   │   └── d06484cff6abfd814bce6a8391fe12d0b8355c
│   │   ├── 5e
│   │   │   ├── 4add19000dc32d51713f795fd4ccc4d4d7bd2b
│   │   │   ├── e1b1408192bb90d2e0b0791547358cbdd01e7e
│   │   │   ├── eff15960ef95424b45d382bca60e9056f362ad
│   │   │   └── fabe0dee2546d3d4f2a189a0c615e808b5e2bc
│   │   ├── 60
│   │   │   ├── 24b1f6a70ae4f23149c62cf321f9f0302af90b
│   │   │   └── a631c20ddb04421ef7ae8dd492bf9e2a0321f3
│   │   ├── 61
│   │   │   └── 833c41b18867afee6d6e0c2af0418eefbc43e5
│   │   ├── 62
│   │   │   ├── 0151799f88f7b0e2997241d0a6e6530cea868e
│   │   │   ├── c871965e05787416dcf3fc34eff79f34fc8a84
│   │   │   └── ff0d2cbd6bf03505dc95569a136e5c24a87f83
│   │   ├── 63
│   │   │   ├── 1133910cffdf7534d63127e6222bca9918bfb2
│   │   │   ├── 3449aabbfae772d657401f70f63c944afd2f5e
│   │   │   ├── 9cb8d72d0df22e46420a79f13610e3d5e3b1c4
│   │   │   └── ffb049a5be5b6552f78cb008ca8a673f3ff861
│   │   ├── 64
│   │   │   └── 77fdadeec18564e1520504bfe7470185d13132
│   │   ├── 65
│   │   │   ├── 032b496ea086ebdb35d2f3ddf07f972857fea2
│   │   │   ├── 29db8925c274638b82bd66ce8053da4be22d34
│   │   │   ├── be101f2cf8ba2c36ac09981df7e0e2adc6e36a
│   │   │   └── cc1b2812ea4d0089840d4615b70c109f577dcb
│   │   ├── 66
│   │   │   ├── 35181aa31bb9d055f002013b135c1a968a45be
│   │   │   ├── 4113748c02e079edbb63a971242c0ebc5d5707
│   │   │   ├── 6655afefe965218576bee2d6bf486bfd01b3c5
│   │   │   ├── a55bef08f26f74e469a305c5d1b54b519713b8
│   │   │   └── da424cd63af5b44697c96bab6dbcea0cdd028b
│   │   ├── 67
│   │   │   └── 075c82a0965e072d2cd437fdedd2c7b623e3cc
│   │   ├── 68
│   │   │   ├── 60a9e6876fe652a7de0005cc5c83c1c2778aa8
│   │   │   ├── 63026254984fa2aed9db6b8f1fcfbfd70c7e92
│   │   │   ├── 6fb67487b95cfe9102a9671d9c9b478856af42
│   │   │   └── 80a6d528cb783b46fb137b6f8ab23e94c5f98c
│   │   ├── 69
│   │   │   ├── 4f96cce5ce4c976608448d9a5a0023b85e2519
│   │   │   ├── ab380a84dffd862889a78c5653dae41d196137
│   │   │   └── ca585b663f0f0bcca8f2ebdfcc1ede9a717736
│   │   ├── 6a
│   │   │   ├── 20fe586add1b9b58ee34737183c1f76433618b
│   │   │   ├── 2179c8bbb318477bbb1c615a29b591231591e7
│   │   │   ├── 43c126cab147c9dd582e88f4179dda269c8ccb
│   │   │   ├── 44986e22687dabb6825fc3e38461f9e94331b7
│   │   │   ├── 61f2a8cd2fc2fb760fb76d53460364df6a003c
│   │   │   ├── 9d8a294d2f81d94c2fbed58c9fcc40c065954d
│   │   │   ├── dbf85970beb4ab7122186c6a88eb0fa6ae40d7
│   │   │   └── ded220a68a2852fd8d9c4663fe7e86eb16ee0c
│   │   ├── 6b
│   │   │   ├── af88ba77e39396ab2ca1af27ad93f1eb63078c
│   │   │   └── e0f91f41a929e0a9e7a0a21ade0a4783ebd172
│   │   ├── 6c
│   │   │   ├── 1235266bff717908d6167e24f2d9c4ec8bc795
│   │   │   ├── 4aa3a60b5fc3bd7479b7a366b9452a2da3d356
│   │   │   ├── be56293c9d1efede9b614d263b8f5c502125a3
│   │   │   ├── cf8aaeeef060532638fe4f1bb71cf903cea942
│   │   │   ├── d7910bac0163aeea855b210eaa395583c793cf
│   │   │   ├── de587099d9f5c738a99cff428d7f000e405f37
│   │   │   └── fd995afd80051db19d8f2256323505534eadcf
│   │   ├── 6d
│   │   │   ├── 15509b36f56a23c19ace16c9cffaf180445095
│   │   │   ├── 4ab287bb2cc05681dee282ebb0cceb9d7c5243
│   │   │   └── d83bf05214be0ca57dd1c3b59da747ac3f9a8d
│   │   ├── 6e
│   │   │   ├── ddf407cdc8eb90542cd66bcad844bf31a97b65
│   │   │   └── eebe23b90fe80b6c6b2149c507264fb7f05bf4
│   │   ├── 70
│   │   │   ├── 08de47761a4ad1e346155fed49cb682d33291f
│   │   │   └── cd9eb853124d3709ecd0a07e4f1fed8fb4b9b4
│   │   ├── 71
│   │   │   ├── 687a7f2bd844d8eba1379cc8599ca294ff87f1
│   │   │   ├── 7d91412fdae65f5608d03630f59b579a0c7ee5
│   │   │   └── 820f4bca42770f23bdf0d5b5f0c4f6e78eb4aa
│   │   ├── 72
│   │   │   ├── b3d8602f70301f5b92c4bac1ccc730cd71d2d0
│   │   │   └── db9ba6662a6b4dbc3737e60c06a9e5c3651140
│   │   ├── 73

In [18]:
import os

def find_empty_and_redundant_folders(root, print_empty=True, print_redundant=True, low_threshold=1):
    empty_dirs = []
    redundant_dirs = []
    low_content_dirs = []

    for dirpath, dirnames, filenames in os.walk(root, topdown=False):
        # Count only files directly in this dir
        file_count = len(filenames)
        subdir_count = len(dirnames)

        # Check if this folder is completely empty
        if file_count == 0 and subdir_count == 0:
            empty_dirs.append(dirpath)
        # Check if it contains only other empty dirs
        elif all(os.path.join(dirpath, d) in empty_dirs for d in dirnames) and file_count == 0:
            redundant_dirs.append(dirpath)
        # Optionally: flag low-content folders
        elif file_count <= low_threshold and subdir_count == 0:
            low_content_dirs.append((dirpath, file_count))

    if print_empty:
        print("\n📂 Completely Empty Folders:")
        for path in empty_dirs:
            print("  -", path)

    if print_redundant:
        print("\n🗃️ Redundant Folders (only contain empty subfolders):")
        for path in redundant_dirs:
            print("  -", path)

    print("\n⚠️ Low-content Folders (≤1 file):")
    for path, count in low_content_dirs:
        print(f"  - {path} ({count} file)")

    return empty_dirs, redundant_dirs, low_content_dirs

# ✅ Run it on your C-Elegans project folder
if __name__ == "__main__":
    PROJECT_ROOT = "/home/rohit/Desktop/C-Elegans"
    empty, redundant, low = find_empty_and_redundant_folders(PROJECT_ROOT)

📂 Completely Empty Folders:
  - /home/rohit/Desktop/Projects/C-Elegans/_extracted_txt/Ce_synapse_UNIX/Ce_synapse/Albertson_Fig/neurons
  - /home/rohit/Desktop/Projects/C-Elegans/_extracted_txt/Ce_synapse_UNIX/Ce_synapse/White_Fig/neurons
  - /home/rohit/Desktop/Projects/C-Elegans/_extracted_txt/Ce_synapse_UNIX/Ce_synapse/White_Table/neurons
  - /home/rohit/Desktop/Projects/C-Elegans/_extracted_txt/database.297.4-0/wquery/geneace
  - /home/rohit/Desktop/Projects/C-Elegans/extracted_tar_archives
  - /home/rohit/Desktop/Projects/C-Elegans/data/lineage/processed
  - /home/rohit/Desktop/Projects/C-Elegans/data/exports
  - /home/rohit/Desktop/Projects/C-Elegans/data/neuroml/circuits
  - /home/rohit/Desktop/Projects/C-Elegans/.git/objects/info
  - /home/rohit/Desktop/Projects/C-Elegans/.git/objects/pack
  - /home/rohit/Desktop/Projects/C-Elegans/.git/refs/tags
  - /home/rohit/Desktop/Projects/C-Elegans/.git/branches
  - /home/rohit/Desktop/Projects/C-Elegans/vgae_outputs/logs
  - /home/rohit/Desktop/Projects/C-Elegans/vgae_outputs/vgae_outputs/overnight_analysis
  - /home/rohit/Desktop/Projects/C-Elegans/generated_graphs
  - /home/rohit/Desktop/Projects/C-Elegans/outputs
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ws268_lod_203
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS247
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ws268_lod_1274
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_pseudogenes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS247
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ws268_lod_509
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_genes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_ncRNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ws268_lod_81
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ws268_lod_32
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_ncRNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_cDNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS244
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS247
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_ncRNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_cDNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS244
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS244
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_cDNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_genes_WS247
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_genes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/t_muris_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_ncRNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_cDNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_genes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_pseudogenes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_ncRNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/c_nigoni_genes_WS264
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_repeatmasker
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brenneri_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ws268
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS244
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_ncRNAs_WS270
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_ncRNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/s_ratti_cDNAs_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_pseudogenes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_cDNAs_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/elegans_genes_WS255
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_genes_WS265
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/pristionchus_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/brugia_pseudogenes_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/remanei_cDNAs_WS297
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/ovolvulus_pseudogenes_WS260
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/japonica_cDNAs_WS250
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_ncRNAs_WS245
  - /home/rohit/Desktop/Projects/C-Elegans/ExtractedFiles/briggsae_ncRNAs_WS270

In [19]:
import os
import shutil

# Set this to the root of your project directory
PROJECT_ROOT = "."

# Folders flagged for deletion (relative to PROJECT_ROOT)
folders_to_delete = [
    "data/temp",
    "data/embeddings/old",
    "data/connectivity/temp",
    "data/legacy_or_unknown/old",
    "data/results/temp",
    "data/metrics/unused",
    "data/utils/tmp",
]

# Optional: Folders to review manually
manual_review = [
    "data/metadata/misc",
    "data/utils/notes",
]

deleted = []
skipped = []

for rel_path in folders_to_delete:
    full_path = os.path.join(PROJECT_ROOT, rel_path)
    if os.path.exists(full_path):
        try:
            shutil.rmtree(full_path)
            deleted.append(rel_path)
        except Exception as e:
            skipped.append((rel_path, str(e)))
    else:
        skipped.append((rel_path, "Path does not exist"))

# Log results
print("✅ Deleted Folders:")
for d in deleted:
    print("📦", d)

if skipped:
    print("\n⚠️ Skipped:")
    for path, reason in skipped:
        print(f"⛔ {path} — {reason}")

if manual_review:
    print("\n🕵️ Manual Review Suggested:")
    for m in manual_review:
        print("🔍", m)

✅ Deleted Folders:
📦 data/temp

⚠️ Skipped:
⛔ data/embeddings/old — Path does not exist
⛔ data/connectivity/temp — Path does not exist
⛔ data/legacy_or_unknown/old — Path does not exist
⛔ data/results/temp — Path does not exist
⛔ data/metrics/unused — Path does not exist
⛔ data/utils/tmp — Path does not exist

🕵️ Manual Review Suggested:
🔍 data/metadata/misc
🔍 data/utils/notes

In [20]:
import os

target_file = "merged_master_graph.gml"
matches = []

for root, dirs, files in os.walk("."):
    if target_file in files:
        matches.append(os.path.join(root, target_file))

if matches:
    print("✅ Found:")
    for m in matches:
        print("📍", os.path.abspath(m))
else:
    print("❌ File not found.")

❌ File not found.

In [21]:
import os

# Define target filenames to search for
target_files = {
    "motif_summary.csv": None,
    "lineage_embeddings.pkl": None,
    "richscore_df.pkl": None
}

# Walk through all files in the project directory
for root, _, files in os.walk("."):
    for file in files:
        if file in target_files:
            target_files[file] = os.path.join(root, file)

# Print results
for name, path in target_files.items():
    if path:
        print(f"✅ Found {name}: {path}")
    else:
        print(f"❌ {name} not found.")

❌ motif_summary.csv not found.
❌ lineage_embeddings.pkl not found.
❌ richscore_df.pkl not found.

In [22]:
import os

keywords = ["motif", "lineage", "richscore"]
matches = []

# Recursively search
for root, _, files in os.walk("."):
    for file in files:
        lower = file.lower()
        if any(k in lower for k in keywords):
            matches.append(os.path.join(root, file))

# Print results
if matches:
    print("🔍 Possible matches:")
    for m in matches:
        print("  •", m)
else:
    print("❌ No partial matches found for motif, lineage, or richscore.")

🔍 Possible matches:
  • ./lineageexploration.ipynb
  • ./data/lineage/raw/NeuronLineage_Part2.xls
  • ./data/lineage/raw/NeuronLineage_Part1.xls
  • ./data/root_csvs/motif_participation_profiles.csv
  • ./data/root_csvs/motif_null_trials.csv
  • ./data/root_csvs/neuron_motif_roles.csv
  • ./data/root_csvs/merged_lineage_table.csv
  • ./data/root_csvs/motif_global_counts_labeled.csv
  • ./data/root_csvs/motif_divergence.csv
  • ./data/root_csvs/motif_class_table.csv
  • ./data/root_csvs/motif_global_counts.csv
  • ./data/root_csvs/motif_global_counts_cleaned.csv
  • ./data/root_csvs/motif_enrichment.csv
  • ./data/root_csvs/top_rich_motif_neurons.csv
  • ./data/root_csvs/motif_type_anova_results.csv
  • ./data/root_csvs/motif_scores.csv
  • ./data/root_csvs/motif_counts_with_structure.csv
  • ./vgae_outputs/overnight_analysis/motif_enrichment_sankey.html
  • ./figures/motif_type_boxplot.png
  • ./figures/motif_divergence_heatmap.png
  • ./ExtraData/NeuronLineage_Part2(1).xls
  • ./ExtraData/NeuronLineage_Part1(2).xls
  • ./motif_graphs/motif_11_1_2-2_0.svg
  • ./motif_graphs/motif_9_0_2-1_0.svg
  • ./motif_graphs/motif_2_0_1-0_2.svg
  • ./motif_graphs/motif_3_1_0-1_2.svg
  • ./motif_graphs/motif_10_0_0-0_2.svg
  • ./motif_graphs/motif_4_0_1-2_1.svg
  • ./motif_graphs/motif_15_1_0-2_1.svg
  • ./motif_graphs/motif_1_2_0-2_1.svg
  • ./motif_graphs/motif_8_0_1-1_0.svg
  • ./motif_graphs/motif_14_0_1-1_2.svg
  • ./motif_graphs/motif_13_0_1-2_0.svg
  • ./motif_graphs/motif_12_1_0-1_1.svg
  • ./motif_graphs/motif_6_0_2-1_2.svg
  • ./motif_graphs/motif_7_0_0-0_1.svg
  • ./motif_graphs/motif_5_1_0-2_0.svg
  • ./docs/top_motifs_table.tex

In [24]:
import pandas as pd

# Load substitute files (just show shape and columns)
files = {
    "motif_participation_profiles.csv": "analysis/motif/motif_participation_profiles.csv",
    "merged_lineage_table.csv": "data/lineage/merged_lineage_table.csv",
    "top_rich_motif_neurons.csv": "analysis/motif/top_rich_motif_neurons.csv"
}

for name, path in files.items():
    try:
        df = pd.read_csv(path)
        print(f"✅ {name} — Shape: {df.shape}")
        print("📌 Columns:", df.columns.tolist())
        print()
    except Exception as e:
        print(f"❌ Failed to load {name}: {e}")

✅ motif_participation_profiles.csv — Shape: (1533, 419)

In [28]:
import numpy as np
import logging

# Optional: set up basic logging to cell output
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

In [31]:
import pandas as pd
import networkx as nx
import numpy as np
import logging
import os

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

# Paths
# Paths to your uploaded files
edge_path = 'merged_edges_with_relatedness.csv'
meta_path = 'neuron_metadata.csv'  # or neuron_master.csv
motif_path = 'motif_participation_profiles.csv'
lineage_path = 'merged_lineage_table.csv'
richscore_path = 'top_rich_motif_neurons.csv'
output_path = 'output/merged_master_graph.gml'

# Load data
edges = pd.read_csv(edge_path)
metadata = pd.read_csv(meta_path, index_col=0)
motifs = pd.read_csv(motif_path, index_col=0)
lineage = pd.read_csv(lineage_path, index_col=0)
richscore = pd.read_csv(richscore_path, index_col=0)

# Normalize indices to strings
motifs.index = motifs.index.astype(str)
metadata.index = metadata.index.astype(str)
lineage.index = lineage.index.astype(str)
richscore.index = richscore.index.astype(str)

# Optional: key sanitizer for GML
def sanitize_gml_key(s):
    return str(s).replace("(", "").replace(")", "").replace(",", "_").replace(" ", "").replace("-", "_")

# Build graph
G = nx.DiGraph()
all_neurons = set(metadata.index) | set(motifs.index) | set(lineage.index) | set(richscore.index)

for neuron in all_neurons:
    attrs = {}

    # Basic metadata
    if neuron in metadata.index:
        attrs.update(metadata.loc[neuron].to_dict())

    # Motif participation (sanitize keys)
    if neuron in motifs.index:
        for k, v in motifs.loc[neuron].items():
            safe_k = f"motif_{sanitize_gml_key(k)}"
            try:
                attrs[safe_k] = float(v)
            except:
                logging.warning(f"Could not convert motif {k} value {v} for neuron {neuron}")

    # Lineage values (extract only numeric similarity score)
    if neuron in lineage.index:
        lineage_vals = lineage.loc[neuron].values
        for i, val in enumerate(lineage_vals):
            try:
                if isinstance(val, (list, np.ndarray)) and len(val) == 2:
                    val = float(val[1])
                else:
                    val = float(val)
                attrs[f'lineage_{i}'] = val
            except Exception as e:
                logging.warning(f"Failed to parse lineage value for {neuron} at index {i}: {val} ({e})")

    # RichScore
    if neuron in richscore.index:
        val = richscore.loc[neuron].values
        try:
            attrs['RichScore'] = float(val[0]) if len(val) == 1 else float(val[-1])
        except:
            logging.warning(f"Could not convert RichScore for {neuron}")

    G.add_node(neuron, **attrs)

# Add edges
for _, row in edges.iterrows():
    src, tgt = str(row['Source']), str(row['Target'])
    if src in G and tgt in G:
        G.add_edge(src, tgt,
                   Type=row.get('Type', 'chemical'),
                   SynapseCount=row.get('SynapseCount', 1),
                   Relatedness=row.get('Relatedness', None))

# Save
nx.write_gml(G, output_path)
print(f"✅ Saved merged_master_graph.gml with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")

WARNING: Failed to parse lineage value for VD12 at index 0: VD13 (could not convert string to float: 'VD13')

✅ Saved merged_master_graph.gml with 1633 nodes and 10902 edges.

In [32]:
import networkx as nx
import pandas as pd
import pickle

# Load the graph
G = nx.read_gml("output/merged_master_graph.gml")

# Extract node data
node_df = pd.DataFrame.from_dict(dict(G.nodes(data=True)), orient="index")

# Extract motif features
motif_cols = [col for col in node_df.columns if col.startswith("motif_")]
motif_summary = node_df[motif_cols].copy()
motif_summary.fillna(0, inplace=True)
motif_summary.to_csv("motif_summary.csv")
print(f"✅ Rebuilt motif_summary.csv with shape {motif_summary.shape}")

# Extract lineage features
lineage_cols = [col for col in node_df.columns if col.startswith("lineage_")]
lineage_embeddings = node_df[lineage_cols].copy()
lineage_embeddings.fillna(0, inplace=True)
with open("lineage_embeddings.pkl", "wb") as f:
    pickle.dump(lineage_embeddings, f)
print(f"✅ Rebuilt lineage_embeddings.pkl with shape {lineage_embeddings.shape}")

✅ Rebuilt motif_summary.csv with shape (1633, 418)
✅ Rebuilt lineage_embeddings.pkl with shape (1633, 278)